### ISSUE TITLE
Update Dog fields to cleaner model

### ISSUE THREAD

**Issue by deb761** [Atlas-Assistance-Dogs/atlas-dogs#104]
Remove Latest... fields.  Only track Due....

**Comment by atlasjen** [comment]
remember to look at the formula fields based on date and fix. Or assign to arjinder to fix once we update the model.
We will now have two docs we want, not just the vet health form, but also an xray report.
Vet Health Form
Vet Xray Report

Drop this field: health check failed dog accepted
Change "health check note" to just "notes"

change status as in spreadsheet.
Add "program" just like we have for clients.

**Comment by atlasjen** [comment]
Once fields updated, let arjinder know so she can fix dog layout
