### ISSUE TITLE
rename picklist "position" that is used for program to be "program position"

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#116]
I happened to notice we have 2 picklists named "position" which is a bit confusing as one applies to programs and one applies to contacts.. might be good to name slighlty differently

**Comment by deb761** [comment]
I see one picklist called Positions, and another called Programs.  Where exactly is the duplicate Position?

**Comment by atlasjen** [comment]
you are right.. i no longer see that. we must have cleaned it up at some point. closing.
