### ISSUE TITLE
Improve ContactController tests

### ISSUE THREAD

**Issue by deb761** [Atlas-Assistance-Dogs/atlas-dogs#117]
Change test class name to TestContactController
Move test class to force-app/main/test
Create at least one test per controller endpoint:

1. getPagedContacts
2. getContactsByName
3. getContactsWithPosition

**Comment by deb761** [comment]
1. Move test class to force-app/main/test and rename to TestContactController
     
3. Create test methods for getPageSize (one test method per case):
    1. Call getPageSize when AtlasSettings__c is not defined
        1. Verify the result is correct 
    1. Call getPageSize when AtlasSettings__c is defined
        1.  Verify the result is correct

2. Create test methods for getPagedContacts (one test method per case):
    1. Call getPagedContacts with null searchKey
        1. Verify the results are correct 
    2. Call getPagedContacts will reasonable searchKey
        1. Verify the results are correct 
    3. Call getPagedContacts with really long searchKey
        1. Verify the results are correct 
    4. Call getPagedContacts with negative pageNumber
        1. Verify the results are correct 
    5. Call getPagedContacts with pageNumber 0
        1. Verify the results are correct 
     6. Call getPagedContacts with pageNumber 1
        1. Verify the results are correct 
     7. Call getPagedContacts with pageNumber > number of pages
        1. Verify the results are correct 
     
3. Create test methods for getContactsWithPosition (one test method per case):
    1. Call getContactsWithPosition with position that should have results
        1. Verify the results are correct 
    2. Call getContactsWithPosition with position that should not have results
        1.  Verify the result is an empty list 

4. Create test methods for getContactsByName (one test method per case):
    1. Call getContactsByName with name that should have results
        1. Verify the results are correct 
    2. Call getContactsByName with name that should not have results
        1.  Verify the result is an empty list

**Comment by deb761** [comment]
@kaurarjinder  I can work on this after I finish the FileController tests if you don't have time.

**Comment by kaurarjinder** [comment]
Thanks Debbie!
Though I have made changes to contactController test class. But we don’t
need as we are not using this class and related lwc component. We are not
referencing some of the  methods anywhere.

Thanks!

**Comment by atlasjen** [comment]
closing as no longer needed
