### ISSUE TITLE
file upload issues

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#150]
tested from PR "feature/base-related-list"

- uploaded a file and categorized w/o issue.
- the file did not show in the file list until i refreshed the browser manually
- i chose "edit" on the file after that and then category and type were defaults and not the ones I had set it to.

**Comment by deb761** [comment]
@atlasjen Please retest on devInt.  I am not seeing the problem.

**Comment by atlasjen** [comment]
i actually noticed this worked fine on Dog in my scratch org the other day when testing. Yep just fine in DevInt. Closing!
