### ISSUE TITLE
background check page layout updates

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#153]
**Page layout**
I know you are in the middle of working on this, but we should have a "related files" tab so we can see the actual background check.
Also, please change "Date" to display as "Completed Date"

**New button**
We need a way to upload a file when we say new.

**Comment by atlasjen** [comment]
Completed Date still needs to be changed to Date

In the detail view for background checks, can we hide the "background check name"
![image](https://user-images.githubusercontent.com/66139437/159178029-b1953d84-599b-429e-83a5-95320c0bb7b0.png)

**Comment by deb761** [comment]
It doesn't look like we can hide the "background check name" as part of the package.

**Comment by atlasjen** [comment]
ok. it seemed like some of these views we can hide the default generated ID. It's not a show stopper obviously.
