### ISSUE TITLE
Background check let's you create empty records

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#157]
If you create a new background check, there are no required fields.
It will create a record w the default status and then also adds an invalid file handle.
![image](https://user-images.githubusercontent.com/66139437/145240939-c5777aa4-f538-440c-9d46-663bad2d38b4.png)

If i click on the file, I get this error
![image](https://user-images.githubusercontent.com/66139437/145241034-934151c5-2d25-457d-bbb0-8a48a3a32edc.png)

**Comment by atlasjen** [comment]
checking in on this. I see "Contact" is required but that is it. I am not longer getting the error above, but my contact still has an empty background check
![image](https://user-images.githubusercontent.com/66139437/159177901-cc87d55d-cd32-42ed-8166-d8350eeaf7b6.png

Should also require status (None is default)
Need a way to upload the file in the NEW creation

**Comment by deb761** [comment]
So, two problems I see:

1. If no file is present and you click on the file area, there is an exception.
2. Status is not required.

Should a file be required?  Or just status?

**Comment by atlasjen** [comment]
Yes a file and status should be required on NEW

**Comment by atlasjen** [comment]
I think a file and status are both required. i can see a use case where we change status when a file exists. but these entries are only going to get added when there is a file.

________________________________
