### ISSUE TITLE
Log custom component issue

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#178]
In the Log Component that is a related object under Contact:

I think once we fix the related log issues in #158 this may be resolved. I did try editing a log to change the "role" from submitter to team facilitator but it didn't apply to my contact.. likely due to the bugs in what fields you can choose for a given log type.

Also, do we need a way to see the full log detail or just to add more columns to the default here?

**Comment by deb761** [comment]
Let's close this one and open another if a problem pops up with the updated form.
