### ISSUE TITLE
PAT updates

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#180]
**The PAT schema looks good other than 2 things:**
1) I think we want a "pat number" field that ideally automatically increments so we know is it 1, 2, 3  etc. This is going to be needed for
2) we want a PAT due derived field.  If the previous PAT was 1 or 2, then it is due at the end of the same quarter the following year. So if in Jan 2021, then due by end of March 2022.  If the previous PAT was 3 or later, it is due EVERY other year, same logic as quarter
3) I realized Role goes away.  We just need to require dog, client, assessor on each.

**The PAT new form should have more required fields:**
* status, location, client, dog, assessor
* "Assessor" then becomes a required field

**The PAT related pane for contacts should have an easier way to see the attached PATs.** 
right now you have to choose edit and can scroll to the files. can it have a link to the pdfs and let them be brought up?

**Comment by deb761** [comment]
How about we put in the PAT number field and mark fields as required for 1.0, and leave the auto incrementing for after this release.

**Comment by atlasjen** [comment]
so in this release we add "PAT instance" and "PATDue" and the person can manully set them when uploading the file

**Comment by deb761** [comment]
So, PAT's are per Client-Dog team, right?  Shouldn't the next PAT due and the count be applied to the client, not the PAT object?

**Comment by atlasjen** [comment]
Maybe it should be ‘validuntildate’ or ‘expiration date’.. we want to be able to easily answer the question when are pats expiring across all clients..

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by deb761** [comment]
I think we put the PAT due date in the contact object, that would reduce the number of objects to query.

**Comment by atlasjen** [comment]
but the PAT is for the team.. i'd rather keep it w the team.. vs having some PAT things w team and some w contact.
________________________________

**Comment by deb761** [comment]
Agreed.
