### ISSUE TITLE
update File types for Contact/Dog

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#181]
Note, I believe the Emergency Contact goes away on all as it becomes a related record instead, right?
It is also my assumption we can do reports based on the presence of these files and their date stamps. Is that correct or do we need to explicitly add those fields?

Update File types as follows (assuming above is correct)
**Volunteer:**
we just want these two:
Volunteer Application
Volunteer Agreement (was Media and Liability Release)
**Board**
add:
Board Agreement (was Media and Release Agreement)
Resume
**Team Facilitator**
Add "TF Lead Application" as a file type
**Client**
In addition to Client Application, now add Client Pre-Application
In addition to Assistance Dogs Set in Motion Application, now add Assistance Dogs Set in Motion Pre-Application
**Staff*
Change Media Release to "Employee Agreement"
**Team Facilitator Lead**
remove this category altogether
**Dog**
Add "Vaccinations and Exams"
Remove "Other Vet records".. we have an implied other if they don't pick a type

**Comment by deb761** [comment]
Do you want to put Resume as a type for Volunteers?  I remember you asking for mine, and asking for other tech volunteer resumes.

**Comment by atlasjen** [comment]
Yes!
________________________________

**Comment by atlasjen** [comment]
And if Board didn't have Resume, add it there too. thanks!

**Comment by deb761** [comment]
<img width="661" alt="image" src="https://user-images.githubusercontent.com/9601218/162645130-d905f148-22f0-4da9-b2a9-aa4bd814cdff.png">
<img width="661" alt="image" src="https://user-images.githubusercontent.com/9601218/162645398-555bffd4-7a63-4f1b-9813-1ab2bca5d6ec.png">

<img width="661" alt="image" src="https://user-images.githubusercontent.com/9601218/162645214-bb5e0358-3e15-4b13-bbac-9c7756ad27f4.png">
<img width="661" alt="image" src="https://user-images.githubusercontent.com/9601218/162645275-b08b796d-c1b8-43bf-8046-5ad606cfcb69.png">
<img width="661" alt="image" src="https://user-images.githubusercontent.com/9601218/162645288-57a27f7e-3b81-4f3c-b454-2c863129c213.png">
<img width="661" alt="image" src="https://user-images.githubusercontent.com/9601218/162645297-c514c339-ba45-44a8-9937-a09cd7a90ced.png">
<img width="661" alt="image" src="https://user-images.githubusercontent.com/9601218/162645380-05a82876-1a73-48db-8d4e-096bd8ba0619.png">

**Comment by deb761** [comment]
Would it make more sense to have categories for 'Teams Set in Motion' and 'Assistance Dogs Set in Motion' rather than having additional types for their Applications and Agreements?

**Comment by atlasjen** [comment]
So since you went to the trouble of putting the type in front of most, to be consistent should be put 
"Staff" "Board" and "Volunteer" in front of their respective ones?

Also, if you want for shorter abbreviations
ADSiM = Assistance Dogs Set in Motion
TSiM = Teams Set in Motion

----------

**Volunteer, Board and Staff**- we still need this form:
Emergency Contact , though let's call it "Contact Information"
And... we can actually end up w those from Trainers, Clients, TF's too if we get updated info, so why don't you add it to all.
---------------

 **Client**, since there are various client types lets make "Application" "Client Application"
Also there are 
Assistance Dogs Set in Motion Pre-Application and
Assistance Dogs Set in Motion Application
--------------
Under **Team Facilitator**, we don't need

Application AND TF Application.
Let's just keep TF Application.
----
Under **Trainer**

rename Infraction Notice (as applicable) to "Infraction Notice"
---------

**Comment by deb761** [comment]
I was in the process of taking Client, Trainer, TF, etc off.  Each contact can have multiple documents with the same Category and type.

**Comment by atlasjen** [comment]
ok that works too. Which means I understand now why you were thinking diff ones for ADSiM and TSiM. We can do that too.
________________________________
