### ISSUE TITLE
Create ReceivedDate field for each file upload type

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#184]
maybe do this at the same time as #181 
for every file type, we need to populate a ReceivedDate field so we can use it for reporting.

I suggest a format of <category><document type>ReceivedDate
So for example, ClientPreApplicationReceivedDate, VolunteerEmergencyContactReceivedDate

these should be populated w a trigger anytime one of these files is uploaded.

If the file isn't given both a category and type then we don't set a date.

**Comment by deb761** [comment]
I think this can wait for 1.1.  After all, the current process is manual.

**Comment by atlasjen** [comment]
Clarification, these need to be on the Contact object so we can display in reports. If we need to delay trigger to 1.1 we can do that.

**Comment by atlasjen** [comment]
We can’t report on them w/o these… and woukd need to figure out how to backfill . Even if it’s filled out manually we need to add these fields. Can add the trigger to 1.1

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
