### ISSUE TITLE
Add V4S - volunteers for salesforce

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#185]
In researching, i think the free volunteers4salesforce app will get us a lot. It was actually installed in our old instance but i didn't understand what it did.
More data is here, including their data dictionary.
https://powerofus.force.com/s/article/V4S-Data-Dictionary

For this 1st release my question is, can we add it and in this release all we are doing is using their custom volunteer related fields instead of our own.
We would replace these Contact fields we created:
Volunteer Background  -> their field Volunteer Skills
Volunteer Focus  --> their object Volunteer Job
Volunteer Interview Notes  -> their field Volunteer Notes
Volunteer Status --> their field volunteer status

The only thing it doesn't include is background check info (volunteer access) so we can just keep that the way we have it... which is great as that is the one thing we did that is custom on volunteers!

It does add fields to Lead, so sandeep would need to map to those for the contact us form, but that's fine. they will automatically convert when converted to a contact.

Then in subsequent releases we can figure out a bunch of other website integrations/using it/volunteer tracking etc.
I would just rather do the import to the fields once and this gives us a way to solve a lot of the volunteer mgmt issues we are trying to figure out.

Package deployment implications?

**Comment by atlasjen** [comment]
this has been installed in devint w/o issue. Once we know it will deploy in cumulus to scratch orgs, will also install in staging and prod.

**Comment by atlasjen** [comment]
Update, since i've been a bit unsure where this is at.
At present V4S is NOT formally installed as a package in the scratch orgs. We do however maintain some of the fields that were installed with it, essentially anything GW_Volunteer on contact.

Interestingly neither is the Power of Us Hub, though it is in all of our other orgs, devint staging and prod.
Once installed in the scratch orgs we should see
![image](https://user-images.githubusercontent.com/66139437/163691516-9d1b842d-1608-49b8-8f43-a81243534284.png)

**Comment by deb761** [comment]
V4S is part of dev now.

**Comment by atlasjen** [comment]
Details on fields:
**Volunteer Status**
Drop contact.volunteer status.
Use GW_volunteers_volunteer_status with the following updates.
Rename "New Sign up" to "Onboarding"
Rename "Prospective" to "Initial Inquiry"
add "None"

**Volunteer Skills**
Let's drop their list and start with the picklist "Volunteer Focus". We will be narrowing that down and changing it, so not sure if you are able to just reassign it to that pick list or need to enter manually. If manually, then wait. if it's easy to just assign to what is in volunteer focus, do that.

**Comment by deb761** [comment]
It's not incredibly painful to change a picklist before we put data in.  But looking through Volunteer Focus values, it seems they are more jobs than skills.

I'd suggest using something that would help align volunteers with jobs (which I created matching Volunteer Focus):

1. Administrative
2. Accreditation (is that Administrative?)
3. Branding and Marketing
4. Certification
5. Client Operations (Organization?)
6. Financial Operations
7. Documentation
8. Content Creation/Editing
9. Outreach

**Comment by atlasjen** [comment]
Here are the fields we want for Volunteer Skills:
I would say let's just make them alphabetical.

Marketing and Branding
Sales
Website development
SEO
Outreach/Networking
Fundraising/Grants
Medical/Mental Health 
Financial/Bookkeeping
Legal
Education/Course Development
Technology/Infrastructure
Writing/Communications
Project/Program Management
Nonprofit Leadership
Dog Training/Behavior/Veterinary
Disability Advocacy
Administration
Photography/Videography
Social Media
Graphic Design
