### ISSUE TITLE
Dog fields

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#190]
For display purposes lets add

*Age (Years)- this would be a decimal like 1.5
I'd like to be able to show this in the list of all dogs vs months
![image](https://user-images.githubusercontent.com/66139437/163689428-0c8cdb9e-b036-4583-9090-b3b2aecc2a7e.png)

*Health Care Record Status Summary- 
   we used to have this, essentially a rollup of what was in the health care record status field. If everything in it was good, then the summary is good. if any one thing is in "due soon" stage but rest was good, then status is "due soon". if any one thing in "late" stage, status is "late".  I'd like to be able to add this to the top level detail for Dog next to where it has the overall status so it has Status and Health status summary both.

![image](https://user-images.githubusercontent.com/66139437/163689387-f9dbd112-354a-4563-8b20-383c7be87051.png)

**Comment by deb761** [comment]
I restored the ExpiryDateStatus field, which shows Good or Expired.  I'd need a definition for "due soon".

**Comment by atlasjen** [comment]
what is it presently for due soon on the current ones? 30 days? 45 days?
i'd just use the same thing for the rollup

**Comment by atlasjen** [comment]
The Age (years) looks good in the list view for all dogs.
The health record status looks good in the quick view pane for a specific dog.
i am a bit confused on the logic in the HealthCareRecordsStatus__c field. It looks like it doesn't have a 'good' status right now. just bad or good but it shows a half circle in red for good? 

TODO
1- change the page layout to show Age (years) vs age months
2- change the logic for HealthCareRecordsStatus__c to show
           red full circle if expired
           red half circle if due in 60 days  (or orange/yellow)
           green if valid
3- change the logic for ExpiryDateStatus__c to be consistent with HealthCareRecordsStatus__c
    If any one field in the formula is expired, all is expired. red circle
    If nothing is expired, but any one field is due in 60 days, show due in 60 days (orange/yellow circle or red half circle)
    If all good for  > 60 days, green circle

**Comment by deb761** [comment]
All good.  Green checkbox for good, yellow triangle for due soon, red alert for expired.
