### ISSUE TITLE
add addl programs to Program Assignments.

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#211]
we are adding some more values to the picklist Program Assignment.Program.
I don't recall how we are setting expected completion date, but here are some dates and programs if we are actually setting them.

1. rename "Sweet Snoopers Trainer" to "Sweet Snoopers [CEU]" - 3 months
2. Service Dog Selection [CEU]   - 45 days
3. Service Dog Selection [Non CEU]  - 30 days
4. Service Dog Foundations  [CEU] - 45 days
5. Service Dogs Foundations [Non CEU] - 30 days
6. Service Dog Training Bundle [CEU] - 4 months
7. Mobility Disability [CEU] - 45 days
8. Mobility Disability  [Non CEU] - 30 days
9. Medical Disability [CEU]-  45 days
9. Medical Disability [Non CEU]-  30 days
10. Psychiatric Disability [CEU]-  45 days
11. Psychiatric Disability [Non CEU]-  30 days
12. Fitness [CEU] - 45 days
13. Fitness [Non CEU] - 30 days
14. OT Advanced Bundle [CEU] - 4 months
15. OT Advanced Bundle [non CEU] - 3 months

**Comment by deb761** [comment]
Should we add CEU as a property to the ProgramAssignmentDuration metadata?
