### ISSUE TITLE
Not all settings propregating to DevInt and Staging

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#218]
In working on testing mapping fields in staging, I realized some are missing. I then went to check DevInt as well.

DevInt:
- The Atlas Contact Layout is there but isn't assigned to System Admin. I fixed that in DevInt, but we should update that in the script
Everything else seems ok at 1st glance

Staging:
- The Atlas Contact Layout is not updated
- The Contact Object is not updated (for example, missing all of the Recent Date fields)
- The old atlas custom volunteer status field is still present
I am sure there are others. It just looks like it doesn't have the latest update.

**Comment by deb761** [comment]
The default page layout is profile dependent, and profiles don't package well.  I suggest we update these after installing the package in staging, and set them manually in DevInt.

**Comment by atlasjen** [comment]
closing.
