### ISSUE TITLE
can we add a way to set Date to the file upload LWC?

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#219]
I realized a good way to handle setting "Recent" date for the various files. 
One thing is, I realized we may not want a trigger as we will want to be able to set it based on a date of the document itself (such as vet exam) not necessarily the date we upload it.

So.. can we add a field to the file upload that pre-populates w/ today's date but then the person uploading the file can change?
This would be super helpful to have in place as we get this new data in. Is this a small or big ask?

**Comment by deb761** [comment]
Merged in with [PR224](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/pull/224)
