### ISSUE TITLE
Contact object updates

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#220]
Discovered these while debugging inserts/exports
**Let's add some fields:**

1.  Preferred Language (single select)
2.  Alternate Languages (free text field)

Here is a picklist for Preferred Language picklist- these are in the lists of most common, in order of most common in US (at least the top ones are). But maybe we just do English and then the rest alphabetical?

- English
- Spanish
- Chinese
- Tagalog
- Vietnamese
- Arabic
- French
- Korean
- Russian
- German
- Italian
- Portuguese

3.  Middle Name and Suffix. These already exist, we just need to enable them

![image](https://user-images.githubusercontent.com/66139437/167967807-0c886e99-613e-4063-bfec-5ae218e1be40.png)

---

**Last Received Date Field changes:**
Change "Puppy .." to  "Puppy Raiser ..."
![image](https://user-images.githubusercontent.com/66139437/167966744-60895944-97d3-4c3f-a0e3-e37b8df14fa5.png)

For Contact Form, we don't need to have different last received for the different roles. Let's just save 1 date for contact form.
So remove:
![image](https://user-images.githubusercontent.com/66139437/167966957-94c65e44-4e10-4151-887a-7dfd079e3d01.png)

and just make it Last ContactForm  ContactFormReceived__c

Any of these would update the same record and same date.
So "Contact Form" could be an option if "None" is selected as the category OR we could add it to all Categories. Whichever is easiest.

I noticed it is not currently available under TSiM, ADSiM or Staff 

It can then go  to the page layout here:
![image](https://user-images.githubusercontent.com/66139437/167967952-6674a47e-213d-4365-a597-c23f173490e9.png)

---

**Pronoun Picklist**
can you capitalize these? I just think it looks better in the data
They/Them
He/Him
She/Her

also, right now the fact that the actual value is different than we get in our forms means we need to postprocess. I am doing that for dataloader, but not sure if that is viable for form assembly. For example, the actual picklist value for "They/Them" is "They". So i have to munge the data to have it load properly. Would it work to have  the picklist values match the full display value? I may hate myself for this as that means i am back dealing w/ "/" for import, but i think it is less extra processing.

---

**Position**
It appears Volunteer is set by default. We should have it blank/None by default

**Comment by deb761** [comment]
The test I wrote look good.  So does the end-to-end test I did.

**Comment by atlasjen** [comment]
ok.. so should I try again on the PR?
________________________________

**Comment by atlasjen** [comment]
@deb761  I think these are all resolved in most recent checking other than (3) which doesn't appear to have been set.

**Comment by deb761** [comment]
3 is configuration settings, and I haven't been able to setup the scratch orgs for it.  I have a mdapi file, but it doesn't seem to work on the scratch orgs.

I was able to fix the cleanup script and the sample data.

**Comment by atlasjen** [comment]
Included in beta release 1.0 (Beta 7)

**Comment by atlasjen** [comment]
Included in production release 1.0
