### ISSUE TITLE
Relationship object updates

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#222]
1. Let's go ahead and restore the default relationship types (while keeping our custom ones). we can have more than 1 relationship between individuals (don't add dog though, i think that would be confusing w/ our other relationship of dog)

2. Remove "Facilitator" as a type. it is redundant with Team Facilitator

3. Add some reciprocal relationships
to do this go to Settings, NPSP Settings
![image](https://user-images.githubusercontent.com/66139437/168187214-cfa4f704-6d4e-49e5-8e42-127940d4644c.png)

Relationships, Reciprocal Relationships
![image](https://user-images.githubusercontent.com/66139437/168185598-c7c66866-25b1-4e97-9b0a-2a0656845f8b.png)

**So this is weird, the various default recipricol relationships are in DevInt, but NOT in the scratch org. Any clue why?**
Here are the fields to enter, left to right for new ones:

- Volunteer Lead, Volunteer, Volunteer, Volunteer
- Primary Emergency Contact, Client, Client, Client
- Secondary Emergency Contact, Client, Client, Client
- Handler, Client, Client, Client
- Facilitator, Client, Client, Client
- Team Facilitator Lead, Client, Client, Client

**Comment by deb761** [comment]
DevInt would have the relationships that have been updated, the scratch org would have the defaults.

**Comment by deb761** [comment]
The Reciprocal relationships are data, not meta-data, so they won't be part of the package.

**Comment by atlasjen** [comment]
ok.. so is there anything to do here or do we close this?

**Comment by atlasjen** [comment]
closing as i don't think we need to do anything
