### ISSUE TITLE
Trigger to populate npe01__HomeEmail__c

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#225]
We need to ensure npe01__HomeEmail__c and Email are always the same.
Ideally we just have Email be the one that is displayed and able to be populated via the UI and be what we map from forms.

This is necessary for NPSP matching rules to work

**Comment by deb761** [comment]
So, if npe01__HomeEmail__c is updated to match every time Email changes, we should be safe?

**Comment by atlasjen** [comment]
sounds perfect. yes.
________________________________

**Comment by atlasjen** [comment]
Included in beta release 1.0 (Beta 7)

**Comment by atlasjen** [comment]
Included in production release 1.0
