### ISSUE TITLE
New contact form

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#233]
once we have the configuration in, add Middle Name and Suffix as fields that can be set.

**Comment by deb761** [comment]
Yes, but if you input Name, it should break it up into FirstName, MiddleName, LastName, Suffix.

When I tried a new scratch org with the additional fields (and I included enabling the addition), the sfdx push failed.

**Comment by deb761** [comment]
Cool.  Salesforce breaks out the fields:
<img width="744" alt="image" src="https://user-images.githubusercontent.com/9601218/169901186-6a6bd1c8-30a6-4664-85b5-7d3a14b5670c.png">

**Comment by atlasjen** [comment]
yeah i saw that in the default form on staging. so we just need to merge that data into our new form.
We don't need salutation, FYI.

thank you!
________________________________

**Comment by deb761** [comment]
Sorry, we're going to get Salutation unless there's some setting that will hide it.

**Comment by atlasjen** [comment]
lol. ok then! so are you going to use this form and just add our other stuff to it?


________________________________

**Comment by deb761** [comment]
Yes.

**Comment by atlasjen** [comment]
Can me make salutation optional ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by atlasjen** [comment]
can you see if that works? everywhere i read name is generated from first, middle, last, suffix.
It can be set manually, but unless custom code is written, it will not populate the other fields.

It wonder if it is a scratch vs sandbox org thing.

If including middle and suffix is just too complex, we can pull it out of all of our forms, i just know having at least middle name is really standard for uniqueness on names.
________________________________

**Comment by atlasjen** [comment]
let me figure out if this is even relevant any more
