### ISSUE TITLE
minor contact data model updates

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#240]
In reviewing the latest data w/ Molly and Rosa and walking through the import process they would like these additional fields.
This should be able to be the last data model change and then we create a production package. I am going to go through the process to fully import a team facilitator in staging using the approach Molly and Rosa and i agreed on and will see if there are any kinks, but we should be set. 

1)
Contact.TrainerFinancialNotes 
Contact.ClientFinancialNotes

They should be free text and appear  at the end of the Trainer and Client page layout sections respectively

2) 
We have another file type for Trainer
TrainerRateWorksheet  
We don't need to have a date we display associated with it, but we will store it in their records.

**Comment by deb761** [comment]
We had taken all the note fields out with the preference to use Salesforce notes.  Are we sure we want to change that?

**Comment by atlasjen** [comment]
AH right.. OK . never mind. i see where the notes populate.
