### ISSUE TITLE
Contact views

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#248]
Let's make the default contact view this:
![image](https://user-images.githubusercontent.com/66139437/174459914-65d77ae3-b54d-45b5-9c19-542ce3a6d26b.png)

then for the specific pre-saved views
REMOVE "positions"
ADD
Add two columns
relevant status
last agreement date

*for client, for example, it would look like:
![image](https://user-images.githubusercontent.com/66139437/174460060-cde80ed3-4f71-4eda-bc4c-6901debc8372.png)

* for volunteer, also add "Reports To"

So, for example, for Volunteer it would look like
![image](https://user-images.githubusercontent.com/66139437/174459990-91bf3085-81cf-453e-b129-b2f600cf29ec.png)

**Comment by atlasjen** [comment]
per #249 we would want to display these valid until fields vs the last agreement date for Client, Trainer, TF, Board.
For volunteer and the others, last certification agreement date works.

**Comment by deb761** [comment]
For client, the valid until field is really in the Team object.

**Comment by atlasjen** [comment]
looks good with PR #246. If you add the ClientValidUntil to contact then we can display it here and this can be closed.

**Comment by atlasjen** [comment]
resolved. closed.
