### ISSUE TITLE
Contact fields

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#249]
We need to be able to easily report on when a trainer or team facilitator needs to renew.
I was thinking we'd use the dates on the agreements, but we likely should have CertificationValidUntil dates 

TrainerCertificationValidUntil
TFCertificationValidUntil
ClientCertificationValidUntil  = PAT Valid Until
BoardTermValidUntil

We already have this covered for clients under the Team (PAT Valid Until)

**Comment by atlasjen** [comment]
Update..
let's make some of these derived

TrainerCertificationValidUntil = date of latest certification agreement + 12 mo
ClientCertificationValidUntil = date of latest certification agreement + 12 mo

TF and Board will still be manually set.

**Comment by deb761** [comment]
There's a problem with ClientCertificationValidUntil.  I can't create a formula field that derives that from Team, since it isn't a direct lookup.  I'd have to make it a regular field and set it off the Team field.

**Comment by atlasjen** [comment]
Gotcha. Let’s hold on that this week . Im out of town w/o a computer. I know we have it on team, just thinking being able to access/query via client might be handy.. we will hit rare cases where silent is part of more than one team.. which is why we did team.

Once we have reporting dashboards I think we can more easily find status

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by atlasjen** [comment]
OK.. I see you added the other valid untils until with PR #246 . 
Let's go ahead and add the ClientValidUntil as you describe, but having it be triggered by what is set on Team.
then this issue can be closed.
