### ISSUE TITLE
New Lead form missing Lead Interest

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#253]
The New Lead form is missing "Lead Interest" as a field we can set.
It is in the page layout for lead.

**Comment by deb761** [comment]
It's there, but you might have to scroll down in the form to see it:
![image](https://user-images.githubusercontent.com/9601218/174684954-4bfa462f-9c22-4c4f-b766-fa7bdfe0bbf3.png)
