### ISSUE TITLE
We need to add demographic data for contacts

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#254]
We need to add demographic data for contacts.
We will definitely be wanting to protect access to it.
I am thinking we update the Contact Form and people can add the data there if they choose to.
**@debbie: I am not seeing any built in demographic fields so wanted to check w/ you on this and see if you see any.**

I am waiting to hear back from the people in the board who are working on this about exactly which categories we will include, but most likely:

Age
Gender
Education
Marital status
Race
Ethnicity
Religion
Language
Veteran Status
Disability Status

We are going to have people complete updated Contact Forms w/ this info and then we can use dataloader to get those in.

**Comment by deb761** [comment]
1. Both Race and Ethnicity are pretty ambiguous.  What I see in most surveys overlap the two.  When I see a survey, I put Human.  And really, there are no races, but there are ancestral origins.....
2. Some of these I can fill in as yes/no/refuse, but the rest.......

**Comment by atlasjen** [comment]
Let's go with adding these. 
Field display names are in bold.
Please use the wording as is and in this order unless i have a typo.. this come from researching best practices. and yes, I know you hate this!

Once these are in, I can play w the order of how they display in the page layout. A lot of these we will not display or we would limit who they are displayed to based on permission/role.

### Race/Ethnicity
Options (multiselect)
* American Indian or Alaska Native
* Asian or Asian American
* Black or African American
* Hispanic, Latinx, or Spanish origin
* Middle Eastern or North African
* Native Hawaiian or Pacific Islander
* White 
* Another race or ethnicity not listed
* Prefer not to answer

### Specified Race/Ethnicity
(text field)

---

### Gender Identity
Options (single select)
* Woman/female
* Transgender woman/female
* Man/male
* Transgender man/male
* Non-binary/gender queer
* Agender
* Prefer to self-describe
* Prefer not to answer

### Specified Gender Identity
(text field)

---

### Sexual Orientation
options: (multiselect)
* Asexual
* Bisexual
* Heterosexual/straight
* Homosexual/gay/lesbian
* Queer
* Prefer to self-describe
* Prefer not to answer

### Specified Sexual Orientation
(text field)

----

### Ability Status
Options (multiselect):
* Vision impairment
* Hearing impairment
* Learning disability/cognitive processing disability
* Chronic Medical illness
* Psychological disorder
* Mobility impairment
* Sensory processing disorder
* Intellectual disability
* None/do not identify with a disability
* Prefer to self-describe
* Prefer not to answer

### Specified Ability Status
(text field)

### Ability Accommodation
options (multiselect):
* Fragrance free environment
* Quieter spaces
* Darker spaces/No bright or flashing lights
* Screen reader
* Closed captions
* American Sign Language
* Attention to food allergies
* Wheelchair/walker accessible spaces
* Seating/minimize standing or walking
* Large print
* Service animal
* None/no accommodation requested
* Prefer to self-describe
* Prefer not to answer

### Specified Ability Accommodation
(text field)

---

### Veteran Status
options (multiselect):
* Veteran
* Spouse/Relative of Veteran
* Active Duty
* None/Do not identify as a veteran
* Prefer to Specify
* Prefer not to Answer


### Specified Veteran Status
(text field)

---

### Pronoun
Then, let's update **Pronoun** to add these options

*Prefer not to Answer
*Prefer to self-describe  <- change from "Specify"

**Comment by atlasjen** [comment]
this is done. closing.
