### ISSUE TITLE
List views

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#257]
Few tweaks.. or show me how to save these myself :) and I can do them. 
Across the board, "recently viewed" should have the same columns as "all". Though, please see below about which one to copy to which.

This is already good on Dog & Teams

- Programs- please have "recently viewed" have the same columns as all. this is just swapping the 2nd and 3rd column.

- CEU- please have "recently viewed" have the same columns as "all"

- Program Assignments- please have "all" have the same columns as "recently viewed"

- Leads- please have "all" and "todays" match "recently viewed"

- Background Check - please have "recently viewed" have the same columns as "all"

- Contacts- please have "recently viewed" has the same columns as "all"

- Accounts, it looks like there are All, and Household accounts but not a filter for Organizational Accounts.
  - Can you add the Organizational Account Filter view
  - Can we have these views (plus recently) all display
![image](https://user-images.githubusercontent.com/66139437/177015750-6a48f72c-0df6-4603-8a0f-381c2bb0b4a8.png)

- Logs
  - Can we make 2 filters one for client and one for team facilitator logs?
  - All and Recent view should show:
![image](https://user-images.githubusercontent.com/66139437/177016003-8a034e58-d66b-4b0b-8a9f-234f1253786c.png)
  - Client view almost same as above (just drop the 1st column, Type)
  - Team Facilitator Log view should show:  
 ![image](https://user-images.githubusercontent.com/66139437/177016084-443594ba-277b-4108-ad6c-15cdcdcb07ac.png)

- PATs- have "all" and "recent" display:
![image](https://user-images.githubusercontent.com/66139437/177016139-9ef10141-ed8d-4821-9ad4-28d5d589e57d.png)

**Comment by deb761** [comment]
I couldn’t find a way to change the columns in “Recently viewed”.

**Comment by atlasjen** [comment]
Weird.. I think it gets a default view

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by atlasjen** [comment]
Check this article out. https://help.salesforce.com/s/articleView?id=sf.customize_recent_records_list_lex.htm&language=en_US&r=https%3A%2F%2Fwww.google.com%2F&type=5
Does this help?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by atlasjen** [comment]
yep. you change the default for a given user, such as System admin and that impacts the recent view.
I will try to do this and submit a PR.
