### ISSUE TITLE
Type does not seem to get populated on Log

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#258]
In testing the list views, i created a couple of logs. I chose Client for one and Team Facilitator for one, but in both cases "Type" is not populated.
![image](https://user-images.githubusercontent.com/66139437/177016189-df7adf91-e625-42af-81dc-2760e38707ec.png)

**Comment by deb761** [comment]
Is there logic I need to follow to determine if a log is a Client or Facilitator log?  Or do we add a field to the form?

**Comment by atlasjen** [comment]
You have that in the initial entry to create a log

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by deb761** [comment]
Looks like we have a duplicate field.  RecordType stores the Record Type.

Another question:  In the new log form used for the contact related lists, how do I determine which record type to create?

**Comment by atlasjen** [comment]
In the new log form you would create the log based on what they check.
That is why ideally it would be Client OR Team Facilitator vs both being an option. For this 1st release maybe we could add some warning text to not choose both? or is it possible to have just one or the other?
![image](https://user-images.githubusercontent.com/66139437/177436667-22c5b2ab-0c3a-4b2a-aacb-25ff0b5271db.png)

**Comment by atlasjen** [comment]
OK.. i see your point on how to determine if it is a client or TF log.
When you click new on the Log related list on a contact, it has the above form.
If you click new on the log object itself, it has a different form:
![image](https://user-images.githubusercontent.com/66139437/177436992-b9831ecd-aa77-4318-8c7c-96571d21a29a.png)

Can we 
1- make them both use the New form you have on contact related items?
2- have them have to call out TF or Client?

**Comment by deb761** [comment]
I think we can do both:

1. Submitter is a checkbox by itself, and Facilitator/Client are radio buttons.
2. We can override the New button for Log so we see the same form as in the related list.
