### ISSUE TITLE
Dog changes

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#260]
**New Dog:**
Remove Vet Clinic from New Dog form.
Add Birthdate to New Dog form.

**Datamodel:**
Deprecate "Activation Date"
Deprecate "Expired"

**Page Layout**
Fix tool tip on birthdate to be MM/DD/YYYY or mm/dd/yyyy something consistent. might as well do the same thing you do for #314 

![image](https://user-images.githubusercontent.com/66139437/184931847-4246b270-b5e8-4cc9-b3e0-2e9d79e0ca9e.png)
-------------------

History:
If I use the "new" dog form, when i search by vet clinic, it does not give me the option to create a new account. Which is weird, since all of the other new forms i see by default let you add new contacts if you can't find one. maybe this is because it is an account vs contact?

![image](https://user-images.githubusercontent.com/66139437/177016311-c30a8781-066b-446f-b63e-2a0779f760ff.png)

Then, let's say i pick an existing account as the vet clinic. Now, I come to look at Related humans and no human is listed:
![image](https://user-images.githubusercontent.com/66139437/177016356-ba604b92-220d-4d73-a1f0-65f285d01186.png)

Semi related, What if a vet clinic has 2 vets and one client uses one and 1 uses a diff one.. so we have 1 organization account but 2 contacts. How do we specify which vet is the related human? I know we wanted to support the case where they had a clinic vs a specific vet, but we also still want to be able to specify a specific vet. Do we maybe need to have them specify Account and Contact here so we can map the person?

We should also make sure this is bringing up the "new" account form that has email included.

**Comment by deb761** [comment]
1. I don't see this problem as a blocker for release, and I don't know how to fix it yet, since is auto-Salesforce stuff.
2. Yes, if the Vet clinic has more than one vet, and the client uses other than the primary vet, or more than one, add the vet to the related humans list.

**Comment by atlasjen** [comment]
OK. moving to next release. work around is to create the vet organziation account first.

**Comment by atlasjen** [comment]
yep. this can wait for 1.2
________________________________
