### ISSUE TITLE
update Relationship.Type in dev

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#275]
This has been manually updated in Staging and prod, but we need to check in to dev to be consistent

Note, this adds "Puppy Raiser" as a type and then reorders.

**Comment by deb761** [comment]
Since this change is for dev and doesn't affect staging or production, I don't think we need it urgently.

**Comment by atlasjen** [comment]
Agreed. I just figured if we are checking things in we should do this at the same time so we don't get out of sync w what is checked in and dev
________________________________

**Comment by deb761** [comment]
Explain to me how one contact has a Puppy Raiser relationship with another contact.  I thought at first this was getting added to the Dog-Human relationships.
