### ISSUE TITLE
Lead custom data not converting to Contact

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#279]
Using the latest code from the PR to fix lead interest and pronoun, i created a lead.
I set both standard pronouns and self-described.
i set an interest.
I see them in the lead.
I convert to a contact. They are not in the contact.

**Comment by atlasjen** [comment]
See: https://help.salesforce.com/s/articleView?id=sf.customize_mapleads.htm&type=5

We apparently need to map these fields.
![image](https://user-images.githubusercontent.com/66139437/179423500-14880a45-7428-450d-8619-b19ccfff851f.png)

I set these in staging. I went ahead and mapped the volunteer ones 1:1.
![image](https://user-images.githubusercontent.com/66139437/179423561-0bdbcfa0-06ad-4e11-8788-4e812c6ea1b3.png)

I assume this should be part of the package, but was testing it in staging.

**Comment by deb761** [comment]
If NPSP doesn't include it, I wouldn't expect it to be part of the package.  I added the settings in prod.
