### ISSUE TITLE
field length for some of the specify/other fields is short

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#283]
I was trying to test importing leads from form assembly and realized we have pretty short character limits on some of the specify/other fields.
I'm really hoping we can still change these..... not sure what our datamodel change limitations are at this point. Sorry i just caught this.

**These max at 20 characters:**
**Lead**
Lead. atlas1__pronounOther__c  is text(20)
Lead.atlas1__LeadSourceOther__c  is text(20)

interestingly the field it maps to in contact is 120
**Contact**
Contact.atlas1__LeadSourceOther__c is text(120)
but pronoun is still 20
Contact.atlas1__pronounOther__c  is text(20)

I also see that the Specified things from demographics may be a bit short- particularly the accommodation one.
![image](https://user-images.githubusercontent.com/66139437/179118576-6d6f55da-1463-4c08-9e23-743a9ca4d4c3.png)

It seems salesforce tends to use Text(128) as its default length for single text fields like title, etc. Let's do that on all of these to be consistent.

It would be wise to go through our custom objects and see where we have "other". I think i caught the remaining ones below.

**CEU**
![image](https://user-images.githubusercontent.com/66139437/179118904-da23dc33-f574-47b9-bf89-857b76ab8492.png)

**Dog**
I like that microchip is unique case insensitive, but 30 seems short
let's just make everything 128 to be consistent, same w/ the dog's name
![image](https://user-images.githubusercontent.com/66139437/179119013-633764ba-223e-47d2-b5ec-a250cb305a79.png)

**Team**
Name maxes at 80. we should likely be consistent and make it 128, that said i don't care that much on that one.

**Comment by deb761** [comment]
Name defaults to 80, so let's leave it.  I'll change the others.

**Comment by atlasjen** [comment]
Ok

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by atlasjen** [comment]
Included in production release 1.1
