### ISSUE TITLE
All Relae

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#289]
I am debugging importing relationships in prod.
I went to look at the toplevel object relatioship view and I can't access "All"

![image](https://user-images.githubusercontent.com/66139437/179661110-95d85b0d-b040-48aa-b6be-d8c6d6733cf8.png)
I assume this is some random configuration.
thanks!

**Comment by deb761** [comment]
I'm pretty sure I can't put this in the package, since it's a view for an object from another package.  I added one to production.
