### ISSUE TITLE
picklist updates

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#290]
**Contact/Lead- i assume they share a picklist**
(1)just saw form assembly has "ASL" as a language option but salesforce doesn't
can we add that at the end of the list?

(2) in the Lead Source, please change "web" to "website" **<-- Doing in Prod directly. Ignore here.**

(3) the value and API name being different are messing w/ things in form assembly.
![image](https://user-images.githubusercontent.com/66139437/179814013-43a5b2bb-6a4a-45de-affb-20b956da63dd.png)
Can you make both "Prefer to self-describe"

**Contact**
(3) Molly wants changes to the Ability Status to be inline w what she is seeing for recommendations. 
Change from :

![image](https://user-images.githubusercontent.com/66139437/179812757-ce081d08-9e4b-416e-9966-cf30f04f4690.png)
to:

![image](https://user-images.githubusercontent.com/66139437/179812881-47326bd8-0fd2-46f8-8bbf-b7844f28dda9.png)

**Comment by deb761** [comment]
ASL = American Sign Language?  Should that be spelled out, or abbreviated?

**Comment by deb761** [comment]
Changes merged into dev with da588e8107e0cc63d4e0b3366cbc5b027fb1cb18
