### ISSUE TITLE
Picklist values for Lead.Interest need to be in prod package

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#297]
For 1.1, manually added these to prod (they already were in staging)
Lead.Interest

Puppy Raising
Standalone Specialty Courses

**Comment by deb761** [comment]
Oh, we will need to munge:

Hey, we encountered this problem while adding a new field into our package.
This is Salesforce official comment:
"Yes, as mentioned by you it is a limitation. Any new packaged picklist values will need to be either manually added after the upgrade or created via a postinstall script with the Metadata API."
https://partners.salesforce.com/partnerCaseDetails?Id=5000M00000s2tgvQAA

**Comment by deb761** [comment]
You should be able to change the name of the picklist value in production, so easy enough to do.
