### ISSUE TITLE
Contact updates- preferred name

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#298]
Feature request from Molly and Niki:
(and many other people in the salesforce community apparently)
Let's add a "Preferred Name" field that can default to a person's first name but we can change to a friendly name other than their legalname. Thinking we autopopulate it with their firstname and then it can be manually overwritten.

The reason I am thinking we'd want it to have a default is I anticipate using it in email templates.

So for example- Instead of Deborah, yours would be Debbie :) 

This would be added to the page layout just under name.

![image](https://user-images.githubusercontent.com/66139437/181384666-5fc612dc-3fac-4818-adbc-15c5bf59c88e.png)

**Comment by deb761** [comment]
Do you need to have the legal first name?  Or can you use the preferred name in the first name field?

**Comment by atlasjen** [comment]
yeah, i think we want both since most people will fill out forms w/ their legal name but then have a preferred name.
this was a request from Molly/Niki as they've been uploading data and working with people.
________________________________
