### ISSUE TITLE
Contact.AbilityStatus picklist updates didn't make it to prod

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#306]
Manually updated in prod. documenting here to fix in release 1.2
The ones in bold were not updated in prod (were correct in staging)

**Blind/Low vision
Deaf/Hard of hearing**
Learning disability/cognitive processing disability
Chronic medical illness
**Mental health condition
Mobility/ambulatory difficulty**
Sensory processing disorder
Intellectual disability
None/do not identify with a disability
Prefer to self-describe
Prefer not to answer

**Comment by deb761** [comment]
We can’t put additions to a standard picklist or a picklist from another package in our package.

**Comment by atlasjen** [comment]
This isn't a standard picklist. this is one of our custom ones.

**Comment by deb761** [comment]
My bad.

**Comment by deb761** [comment]
See comment in #297.
