### ISSUE TITLE
Make LWC for Teams

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#307]
Make a custom LWC for teams, much like we have for Dog or other objects so we don't have separate ones for client and handler and dog.

Another aspect of this is being able to see the status of PATs for the team much more readily.
Right now I have to go to
- contact
- related teams
- pick the team
- go to related items to see the PATs

In this LWC can we display as list items
Team Name, Dog, Handler, Client, Primary Certification, PAT #, PAT Valid until

In the New Team form, add helptext for Team Name to say format is
"[ClientFirst][ClientLast] _ [HandlerFirst][HandlerLast] _ [Dog]"

**Comment by deb761** [comment]
We could add list items to the related list, and a summary LWC.  But the related list has so much useful stuff built in that I am reluctant to override it unless it just isn't doing what you need (like the files list doesn't).

**Comment by atlasjen** [comment]
one workaround is hide Team (handler) and only show Team (client)"

**Comment by atlasjen** [comment]
Note, we don't need a separate list for "handler" just need to see based on team.
