### ISSUE TITLE
Staff updates

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#308]
Contact.StaffStatus picklist is needed
We then also need to update the logic for the quick view that displays status info

Employee
Contractor
Inactive
None

Let's also add "Last Contractor W9" as a field and then add "Contractor W9" as a possible file under staff

And let's change the display in page layout to be "Staff/Contractor Specific Details"

**Comment by atlasjen** [comment]
sure, though how is that different than our various other status fields that are also all optional and have None as an option?

**Comment by deb761** [comment]
Leaving "None" since I can use it to omit items from the page layout.

**Comment by atlasjen** [comment]
confirmed all good

**Comment by atlasjen** [comment]
Nothing shows in the status display area for Staff. I had set the picklist value to employee.
![image](https://user-images.githubusercontent.com/66139437/198173957-209d8241-84f5-46bb-81f8-9a1007024717.png)

**Comment by deb761** [comment]
You never specified a Staff icon, nor requirements for what it would show based on status.

**Comment by atlasjen** [comment]
It was one of the positions so I guess I assumed it would have icons like all of the rest. We can look at that in the next one. not blocking/urgent
