### ISSUE TITLE
tool tip fix on New Contact

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#314]
Little Nit. The tool tip for birthdate should be updated to be MM/DD/YYYY or mm/dd/yyyy or something consistent

![image](https://user-images.githubusercontent.com/66139437/184926049-51f63433-2d25-482c-a195-7608f8532d57.png)

**Comment by deb761** [comment]
I didn’t define a tool tip for it. The error is all Salesforce.

**Comment by atlasjen** [comment]
i realized that once i saw the one for dog was the same.. annoying. can we change it or no?
________________________________
