### ISSUE TITLE
Add classes to permission set

### ISSUE THREAD

**Issue by deb761** [Atlas-Assistance-Dogs/atlas-dogs#319]
These need to be added so standard users can access the Atlas1 classes.

Actually, let's create a AtlasUser permission set which is like the AtlasSuperUser permission set but omits the delete all permission on the objects.

Then AtlasSuperUser can add the delete all permissions.

@atlasjen What do you think?

**Comment by atlasjen** [comment]
The Standard User vs Administrator seems to already control delete permissions, at least on objects like contacts and leads so not sure if that is needed?
We do def need to figure out a heirarchy of permissions for objects and fields w/in them.

**Comment by deb761** [comment]
Closed with #333
