### ISSUE TITLE
Client Last Application Received Date not being set in details

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#320]
In the 1.2 release , a client application was uploaded as was a pre-application earlier.
![image](https://user-images.githubusercontent.com/66139437/186492993-9f1fc86a-5629-461e-a6d7-a572ce40cee4.png)

The pre-application date is set properly in details, but the application one is not, even after several refreshes.

![image](https://user-images.githubusercontent.com/66139437/186494685-e3097b95-f0b3-4506-8702-93cbe562364b.png)

**Comment by deb761** [comment]
That's odd.  I just verified that is set with unit tests.

**Comment by atlasjen** [comment]
Weird. I can test again, but I tested it a couple of times. Note, this was via form assembly. Are we sure it’s not counting on a on click action in the form?
