### ISSUE TITLE
background check file upload component -help text

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#321]
The present Background check file upload component works a bit differently than the general File upload component in that choosing a file and pressing DONE does not actually save the file. you need to do the additional step to save SAVE.

![image](https://user-images.githubusercontent.com/66139437/187344344-843cf6fb-5674-470d-b071-abb36f54f984.png)

This is different than our general File upload LWC that saves once you choose the file and then lets you change the parameters and choose another file to upload w/o having to close the dialog.

**Comment by deb761** [comment]
The save is to save the Background Check, not the file. The content version is created at the upload, the the background check is created and the file is linked when you save.

**Comment by atlasjen** [comment]
can we add a red text tip at the bottom to say "Make sure to Save after uploading your file" so they understand it is a different behavior than the file upload component?

**Comment by atlasjen** [comment]
hmm.. this is still different than how the File Upload one works so that is my concern on confusion. I guess that is just creating the content version where this is also creating the background check.
________________________________

**Comment by atlasjen** [comment]
closing. i think we can live w/o.
