### ISSUE TITLE
need to track inventory clients or dogs have

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#322]
Add Inventory Item- or look at if a standard inventory item exists.

Type [Vest-Standard, Vest-Mobility, Vest-MobilityMag, Vest-StandardMag, Harness]
ID [1,2...]
Size [XS, S, S-M, M, M-L, L, XL, XXL]
Attributes [ free text]
can be related to dog or contact- which could be Jen meaning I have in storage.

So in inventory Quick view
I would be able to see if assigned to someone

**Comment by atlasjen** [comment]
Look at Asset, Product

**Comment by atlasjen** [comment]
Please read through and give me your thoughts.. i think we can skip asset.

### **Create 4 locations**
must check "inventory location"
![image](https://user-images.githubusercontent.com/66139437/193745214-63cb3575-d096-4865-aea4-7b92d877a9c0.png)
### **Create 2 product families in the picklist associated w/ product**
In-Training Vest
Harness
### **Create Products**
set the active status as shown
![image](https://user-images.githubusercontent.com/66139437/193745361-b26fc1de-ce0a-4c3c-afa1-f5049ce48101.png)
### **Create Product Items**
Here are a handful
Note, I'd really like to associate them w a contact right here. Can we add that as a custom field and then access it as a related item for contact? OR even not have it be a related item. just have one of the product item fields be a link to the contact?. Or alternatively, i guess i could put the person's name in location or their real address but that is a clunky hack.  I don't care that much about seeing the vest under the contact view. I care more about seeing where they are in summary, which i could do in the product item view if we could add contact.

![image](https://user-images.githubusercontent.com/66139437/193745655-88385980-a680-4742-a6d2-e529ba46e316.png)

**Comment by deb761** [comment]
You can add Assets to a contact already.  Do you need location?  Asset has an address field that is just not in the default layout.  I'm reluctant to add custom fields to objects when there are standard objects that meet your needs.

**Comment by atlasjen** [comment]
So the asset object adds a lot of data and complexity we don’t need. It also has location and serial number fields that don’t in any way tie into the product ID, so that is another level of confusion.
We are required to set location when we create a Product Item. It’s a required field.
I don’t need to see these are related objects on contacts. Accessing them from product items is fine.
We don’t have all of the Product* b2b related licenses so not all fields and objects that are shown in the standard datamodel are present.
I totally agree on not adding custom data if the present ones meet our needs, but what asset is designed for is way above and beyond how we are using it.
And adding as an asset doesn’t actually help me answer the question of where are all these vests.. that is far easier to do from the list of Product Items.

**Comment by deb761** [comment]
You don’t have Product Item in staging or production.  You do have Asset, and the number of fields is not that many (~ 30 including owner, modified, etc).

I put in the picklist values for you in Prod.  I don’t see a need to have any of the layout stuff in the package.

**Comment by atlasjen** [comment]
I built those out in my scratch org which is why you don’t see them. I was still working through the concept.
Which picklist values did you add to prod?

**Comment by atlasjen** [comment]
can close this. in prod :)
