### ISSUE TITLE
Files LWC updates

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#324]
1. Make it so we can sort by the various columns by clicking on them. Filtering would be an even better nice to have.
Sorting by category and date will be the most needed, but i'd love to be able to do something like
- filter by category and then sort by date or
- filter by date and then sort by category

The sorting when clicking on a column is standard salesforce behavior, so we just need to add to the LWC

2. Limit how many are displayed to say 10, with an option to view all. 
See Jennifer Kolar as a contact for an example w/ a ton of files.
https://atlasassistancedogs.lightning.force.com/lightning/r/Contact/0034x00001COhAUAA1/view

**Comment by deb761** [comment]
How about we show the 10 most recent, that's easy, then show all would take you to a report that would allow filtering.

**Comment by atlasjen** [comment]
Molly says yes that works. it looks like it sorts by date by default. so then yep, the sorting/filtering could happen in the view all list.

**Comment by deb761** [comment]
The report didn't work out.  I was unable to create a custom report on Content Version.  I finally found something that works pretty well.  I limited the #files in the related list to 6 to match the others, then created a component that will show all of them.

**Comment by atlasjen** [comment]
confirmed good
