### ISSUE TITLE
Unable to Delete Log from w/ in Related list in contact

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#325]
I tried this out in prod.
I manually added a client/submitter log to Jennifer Kolar as a test.
I went to try to delete it using the Delete option in the list and it silently does nothing.
![image](https://user-images.githubusercontent.com/66139437/188740715-52c53cb6-88aa-45f0-bd04-e639c10e57f7.png)

Note, if i go to the list of ALL logs as an object, not as a related list, then i can delete them.

**Comment by deb761** [comment]
It's a stupid typo....
