### ISSUE TITLE
tracking people not yet assigned to standalone programs

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#335]
Molly brought up that while we can use program assignments to track people who have been assigned to courses, that doesn't give us a way to track people in the process of applying to the programs.
It also makes it hard for us to know who is active or not for when we need to add/remove access to courses.

One thought was to add Standalone as a position.
The problem is if they are pending in one vs active in another a single status doesn't capture it that well.
However, i know what is offered as standalone courses will change so i don't want to lock us into a ton of statuses.

I did see "Other" sometimes showed up as a position, but I am not sure how. **What does set that?**

So the question is.. even if we needed a report to generate it, we'd want to be able to say
- how many people or who is pending or active for a given standalone course
- who should we remove access from

**Here is one thought:**
What if we add "pending" as a status for Program Assignment? Molly ( or form assembly at the time of mapping in a standalone application) could set this to pending and perhaps add "created date" to the program assignment as well.

Once a person pays, we can change it to pending and set assigned date. This again, can be manual or via form assembly.

We could then  update the File upload types and instead of TSiM have "Standalone Programs" and then the same filetypes.
The filenames themselves would let them distinguish which program.

We would then drop TSiM dates from the client status section on the contact detail page.
I don't think we display anything for the standalone program file dates or add a position for it... or we somehow use other?

thoughts?

**Comment by deb761** [comment]
I like the additional status for folks who have applied to a program.  If you are tracking files for a person/program, why not attach the file to the ProgramAssignment rather than the contact?

The "Other" status indicator is when a contact is 'In Progress' in a program.

ProgramAssignments have expected completion and actual completion dates.

**Comment by atlasjen** [comment]
Well the files being uploaded are  agreements and i'd rather have them all in one place. as people may end up in diff programs or roles and i'd rather not have to look in diff places for their paperwork.

So OK, we add
"Pending" as a status for Program Assignment
"Created Date" as a field for Program Assignment <- automatically set when we create a program assignment

Ah, so Other will appear if someone has a program assignment in progress? That's good to know. Is that for everyone or only if they aren't a client/trainer/volunteer?

Then, we remove TSiM as a file type and change it to Standalone Programs

**Comment by deb761** [comment]
Actually, since the documents are linked, we could link them to both the ProgramAssignment and the Contact.

**Comment by atlasjen** [comment]
We really only need to see them w the contact since that is the much more likely place anyone will look, but good to know if we want to display them w the assignment at some point we can.

**Comment by atlasjen** [comment]
All that is left is
- Add "pending" to the picklist options for program assignment status.

**Comment by atlasjen** [comment]
done in prod. closing.
