### ISSUE TITLE
PAT updates

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#345]
1- need to be able to upload MP4 and MOV
2- need a way to click on it to bring up the full details
3- if access PAT from the easy Nav bar, and choose NEW, there is no ability to upload files
4- if access PAT from the top easy Nav bar, you don't see files that were attached
5- add Files to quick view on right.

the "new PAT" form from PAT

**Comment by deb761** [comment]
We need to discuss what you really need here.

**Comment by atlasjen** [comment]
change scope for this release
- add ability to upload zip, mp4, mov  
- add PAT name link under related  Public Access Tests under Teams so we can open the PAT 
![image](https://user-images.githubusercontent.com/66139437/194197970-bd6c14f1-71f9-488b-86cd-9108effdc1e5.png)
