### ISSUE TITLE
New Puppy Raiser form from Puppy Raiser Logs object doesn't have file upload option

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#368]
This is fine if accessed from the related list under dog.
Under the full list of Puppy Raiser Logs, if I choose new, i can't add a file. It should be optional but we should be able to add it.

Here is it under the object:
![image](https://user-images.githubusercontent.com/66139437/198171596-3f0d5df2-b35e-466f-bab8-9fa5ac47199d.png)

Here is it under the related list:
![image](https://user-images.githubusercontent.com/66139437/198171727-106e7029-2c37-4086-b9eb-10ecf7f8e0b7.png)

**Comment by deb761** [comment]
I will need to override the new button as we do for dog and background check.
