### ISSUE TITLE
New PAT form from object doesn't allow files to be uploaded

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#369]
I can add files when adding via a related list on team, but if i add via the object itself, i don't have the option to add files.

Here is the view from the object list
![image](https://user-images.githubusercontent.com/66139437/198173491-f8706700-c09d-4f70-ace3-fa08b0189b12.png)

vs from the related object under Team
![image](https://user-images.githubusercontent.com/66139437/198173564-cc4f9769-71e0-4856-a26e-b98a9ac6cd46.png)

**Comment by deb761** [comment]
Same as with the Puppy Log object, I will need to override the new button.
