### ISSUE TITLE
Custom report needed to have dog information for TSiM folks

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#382]
While salesforce does support joined reports, they do not support inner joins.. thus your "joined" report is really just two independent reports. lame! lots of open issues on this.

So, thus, i have no way to get the report i want which is very close to this one if only i could do an inner join to see the proper dog on the same line as the person and i want to be able to see and see a few more dog fields.
https://atlasassistancedogs.lightning.force.com/lightning/r/Report/00O4x000007UYoVEAW/view?queryScope=userFolders

here would be the query (ish) select programassignment.contact where ProgramAssignment.Program = "Teams Set in Motion" and programassignment.Status contains ("In progress", "Observer", Pending") and then join that client with client.dog to include the dog name, age, breed, gender

Here are the columns i want to see from programassignment and contact and https://atlasassistancedogs.lightning.force.com/lightning/r/Report/00O4x000007UYfxEAG/view?queryScope=userFolders

From dog i then want: Dog Name, age, breed, gender

This is the one report so far i haven't been able to figure out how to do.

**Comment by deb761** [comment]
Are these folks in a Team with the dog, or are we using a Dog Relationship type of Client to find the connected dog?

**Comment by atlasjen** [comment]
They would all be in a team so, that can be used as a filter.

**Comment by atlasjen** [comment]
I take back what i said. not in a team.
1- find contacts w/. program assignments of TSiM
2- find dog relationship for those contacts

**Comment by atlasjen** [comment]
Need to be able to run and get a CSV. ideally we can schedule this.

**Comment by deb761** [comment]
What columns would you want sorting on?  Any default sorting?

**Comment by atlasjen** [comment]
I'm not sure if it needs a LWC
What i would like is to be able to access them like other built in reports and add them to dashboards.  Same for the various other reports.

Hmm.. I just found this on custom reports and it says we can do related object lookups as well.
https://admin.salesforce.com/blog/2019/build-powerful-reports-with-custom-report-types

I will do some more poking around to see if i can make these reports.

**Comment by atlasjen** [comment]
ok.. been beating my head on this. I cannot do this level of joining/filtering with the built in tools.
how does it work to build report modules that i can add to dashboards in some way?

**Comment by deb761** [comment]
I put together some Apex code that runs the SOQL and outputs a .csv file.

**Comment by atlasjen** [comment]
is there a way to pull this to add to a report?

This looks like it documents how to pull data from reports programmatically, but not the inverse that i want, which is to have a custom report as defined by an apex class.

https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_analytics_intro.htm
