### ISSUE TITLE
need to be able to tell who should have background checks

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#383]
we don't presently have a checkbox on contact to let us know if they need a background check.
This means we don't have a way to form a programatic report of who needs them.
This could be a toplevel field on the contact that we display in the very top section.

We can't just go by who has had them previously, as if they are a TF who isn't working w/ a client, we don't need one but their status may still be certified-active. 

open to other ideas, but just realized we don't have a way to set that is needed.
We could also put it under volunteer, but technically it applies across volunteer, board, TF so better to just have in the upper section to avoid confusion.

**Comment by atlasjen** [comment]
Add "Background check" to Volunteer Access.  Do in prod. then add report.

**Comment by atlasjen** [comment]
done.

**Comment by atlasjen** [comment]
I can form this report: https://atlasassistancedogs.lightning.force.com/lightning/r/Report/00O4x000007UmTwEAK/view
but i can't find a way to have it show me only those who haven't had a background check in the last year.
If i filter it by backgroundcheck.date < lastyear it will match on older reports. Not seeing a way to have it be smart enough to show only those who have none in the lastyear.

**Comment by deb761** [comment]
I was seeing a way to set a date range in a filter in another report.  Try that.

**Comment by atlasjen** [comment]
I am able to filter down to only show ones in the last say year, but that doesn't let me know if they need one again. Maybe they are no longer in a role where one is required. We need a way on the contact level to specify if currently required.
