### ISSUE TITLE
please standarize icons for status

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#387]
Let's standardize icons for status such that
active or certified-active or certified are the same for all.
same goes for inactive, decertified, discontinued, etc would all be the ZZ
Let me know if there are questions on what to consolidate.

Here is what i see for my own record
![image](https://user-images.githubusercontent.com/66139437/202864491-69ab3837-baa7-4dba-a86a-304f8e13427a.png)
you can see that client is different than the others which is a bit confusing

**Comment by deb761** [comment]
You've seen the code for the icons, they are standardized by status.  The client there has "Action needed Soon" status, hence the different icon.

**Comment by atlasjen** [comment]
ok then!
