### ISSUE TITLE
need a way to say who needs to complete CEUs

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#389]
our continued fun of what we can do in standard reports. Here is where i have gotten to.
https://atlasassistancedogs.lightning.force.com/lightning/r/Report/00O4x000007UmU6EAK/view
In this case, I don't have access to the CEU data itself, only the relationships. so I can't run a report that says

Contact, # CEUs in last year

which is what I need to be able to do.

**Comment by deb761** [comment]
You can create a report on CEUs, and group-by Trainer.  Hopefully you can also sum the #CEUs.  Since there aren't any CEUs entered yet, I can't really show you an example.

**Comment by atlasjen** [comment]
ok i figured this out. i was able to create a report that displays the results. closing.
