### ISSUE TITLE
need a way to report when agreements due

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#390]
we are going to hit the same issue for TF agreements, trainer agreements, and so on that i am hitting for CEUs
we need to be able to report on
- when a TF agreement is due
- when a Trainer agreement is due

this will be when the agreement date < LAST YEAR and the position status=active.
i have no way to do this in standard reports. I am looking at what i can do in dashboards as they seem to include additional filtering

**Comment by deb761** [comment]
We are storing the LastReceivedAgreement, can't you use that?

**Comment by atlasjen** [comment]
Ah yes, this one i can do. they are on contacts. ok. closing.
