### ISSUE TITLE
need a way to report when PATs are due

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#391]
I keep hitting this in our data model since the way reports work is you can have 1 primary object and then 1 dependent but not more.

Here is the closest i can get on a PAT report
https://atlasassistancedogs.lightning.force.com/lightning/r/Report/00O4x000007UmadEAC/view?queryScope=userFolders

So again, no way to say focus on just the most recent..

**Comment by deb761** [comment]
I think all you need do is change the filter:
<img width="1892" alt="image" src="https://user-images.githubusercontent.com/9601218/204720123-9ea1d810-e12f-4e03-a1cf-238c03ecd8d2.png">

**Comment by atlasjen** [comment]
yep. this i can do. closing.
