### ISSUE TITLE
Teams/Client/Dog Status

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#395]
In working on a report of how many teams we've ever certified, i realized i can't pull that form a contact's client status as that is their current status.. i need to be able to look at the team... but there is no status.

Here is my suggestion

- we set status on team manually
- there is a trigger to set it on client and dog to be the same thing. If there was already a status on the dog or client, we overwrite it w/ what is in team
- if someone happens to manualy edit the client/dog status later, oh well.  The next time it is updated in the team, we stomp on it.

this is actually staying consistent w/ how we derive certification valid until on the client from the team.

**Comment by deb761** [comment]
To pull a report of the Teams you have certified, you will need to look at the PAT for the teams.  Looking at current status for a team won't give you that report.

You should be able to pull a report on passing PATs, group by Team, and count the number of Teams.

**Comment by atlasjen** [comment]
So i have this general dashboard: https://atlasassistancedogs.lightning.force.com/lightning/r/Dashboard/01Z4x000000VV2UEAW/view?queryScope=userFolders
and the client part of it (top left) is pulling from this report:
https://atlasassistancedogs.lightning.force.com/lightning/r/Report/00O4x000007UmU2EAK/view?queryScope=userFolders

but i realized the client numbers are wrong in the case where a client may have been part of more than 1 team. for example, we have a client, Ellen who certified w/ a previous dog who has since died and is onto her next dog. If i look at client status, I only get status of her current dog (in training). I don't get stats that include her previous dog as decertified. Thus, i need to be looking at teams, not clients to see the full picture.

I have this report of teams and PATs
https://atlasassistancedogs.lightning.force.com/lightning/r/Report/00O4x000007UmadEAC/view?queryScope=userFolders
However, i am not able to filter/group in a way that i can get data on only the latest PAT of each team when it comes to adding to a dashboard.  

I want to be able to answer these things about teams
Qty
# Active
# In Training
# Formerly certified
- i think I can do the above w/ status

Type (primary disability)
# Active
# In Training
# Formerly certified
- i'm not sure how to do this one as when i group by primary disability it counts up the # of pats. ie, we have 1 client w a diabetic alert dog who has tested 2x. when i group by primary disability it shows we have 2 diabetic alert dogs.




for clients in particular, we want to be able to record historical status.

**Comment by atlasjen** [comment]
Follow on from that- Certification Valid Until that is set on the client would only pull from a team who had an active status.

**Comment by deb761** [comment]
What status values do you need?

**Comment by atlasjen** [comment]
Same as client or dog. Let’s make them all the same as what we have for Client status.
So what is set in team is copied to client and dog.
If it’s changed on the client or dog, it doesn’t change the team.

Onboarding
Initial Inquiry  <- Need to add to dog status
In Training
In ADSiM <- need to add to dog status
Certified
Decertified
Discontinued  (need to consolidate this in the dog status from On hold and Inactive)
None

**Comment by atlasjen** [comment]
Status is not showing in the team in staging

**Comment by deb761** [comment]
Updated layout and One Note
