### ISSUE TITLE
Add related files to teams

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#400]
We have a use case of needing to see the files we have for a team all in one place.
1. If a contact has client category files uploaded, and they are in a team, show the client files in the team.
2. if a dog had dog category files uploaded and they are in a team, show the dog files in a team
3. allow the ability to upload client AND dog records from within a team. the dog records should get assigned to the dog and client to the contact.
![image](https://user-images.githubusercontent.com/66139437/207206764-1eccb490-2c1d-4aac-907c-d7c2366519bb.png)

**Comment by atlasjen** [comment]
A little confused on expected behavior.
I made a team in the scratch org.
There are now 3 related file sections
![image](https://user-images.githubusercontent.com/66139437/209057722-662fa546-7098-4461-8dc3-904724483583.png)

Under Teams, Related:
If I upload things to Files (which i can pick Client or Dog as types,_ they do not show in the contact or dog.
If I upload things to Client Files, they do indeed show in Contact.related files.

Under Contact. Related:
If I upload a client category file, it does appear under Teams . related  Client Files
Under Dogs. Related:
If I upload a dog category file it does appear under Teams . related  DogFiles

However, these do NOT appear under Teams. Files.
And if i upload a Client or Dog category file under Teams. files, they don't show in the Contact or Dog. or under Teams.Contact Files or Teams.Dog files in the related tab

It seems ideally we'd just use the Related Files LWC under Teams and filter based on the category (dog or client) vs adding in the 2 addl Client Files and Dog Files sections.

---
I am also able to pick any category i want (trainer, etc) in the Client Files and Dog Files sections under Teams. Related. If we keep these, it seems they should filter to only be their type.. but again, I'd be inclined to say they don't need to be there and we just use Related Files and 'category' under Teams.

---
know issue, but a bit trickier w/ this logic, i can set Dog files on my Contact and Contact files on my dog. If I set a "dog" category file on my contact it shows in BOTH the teams dog and client sections... which does make sense given the logic.
I'd say best is to not display "DOG" as a category in the contact context and not display anything other than "DOG" as a category in the dog context

**Comment by atlasjen** [comment]
I also got this error pushing sample data deploying this to a fresh scratch org:
                    Prepared 80 rows for DataOperationType.INSERT to Log__c.
[12/21/22 20:16:10] Running step: Insert ProgramAssignment__c
                    Creating DataOperationType.INSERT Operation for ProgramAssignment__c using smart
                    Prepared 7 rows for DataOperationType.INSERT to ProgramAssignment__c.
                    Exception in task config_dev.load_dataset

Error: Error on record with id 1: INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST: Status: bad value for restricted picklist field: Pending      
(Status__c)

**Comment by deb761** [comment]
The additional components are a quick and, I thought, a clear way of making these related files visible in the team.  So, you add a file in the Client files, and you see it in the team and the client.  Same with the dog.

Filtering the list of categories based on object type is a good idea, but we have been pushing that off for a future release.

**Comment by atlasjen** [comment]
I like that we can see in both. I think it is just a bit confusing to have related files, client and dog so effectively you see a duplicate of all client and dog files when looking at the team.  I guess we could hide showing the “files” on the team. I’m not sure what files would go there that don’t go to client, dog or PAT.

**Comment by deb761** [comment]
I was also thinking we remove the Files component on team in favor of the Client Files and Dog Files.

**Comment by atlasjen** [comment]
Sounds good.

**Comment by atlasjen** [comment]
as of 2/9 dev main branch, it looks like i can add logs from the client or team and will see in either so considering this closed. It is known issue that since we don't force the logs to be only for defined teams, that the logs that show up in team are filtered by the client and not the client and dog. Once we add that fix in for the logs, we can tighten that logic on what to display in team related logs. Not a 1.4 issue.
