### ISSUE TITLE
Add some more "last dates" and content version types

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#401]
In Trainer we want to split out Reference Letter  document type
to "Client Reference" and "Professional Reference"
and add LastClientReference date  and LastProfessionalReference date
when you delete LastReference date, set it to LastProfessionalReference date

In Client we want to add these document types
"Application Video"  and LastClientApplicationVideo date
"CGC Form" and LastClientCGCForm date

**Comment by deb761** [comment]
Do these client files (Application Video & CGC Form) go with contact or the team?

**Comment by atlasjen** [comment]
team

**Comment by atlasjen** [comment]
In staging:
The trainer date fields are showing in the page layout but the client ones are not.
Neither are showing in the file upload dialog as options for upload

**Comment by deb761** [comment]
Added to Staging and One Note (this is getting really tedious)

**Comment by atlasjen** [comment]
sorry :(
The trainer file types are now showing in new file uploads. They do not show as options when i go to edit a previously uploaded file. possibly related- i had a file uploaded as "client" i went to edit it and changed category to trainer and saved. I then clicked edit again and it still opened up the edit dialog as client. I refreshed the related file list and then clicked edit and it did show trainer as the present category, but still didn't have the new file options.  Note, I tried the edit option again from one created as a "Trainer" category initially and still had the same issue. In edit, the new file types don't show.


The client file types are still not showing in file upload or page layout.

**Comment by atlasjen** [comment]
Checked the latest.
In file upload on NEW- I do see the file types for Client and Trainer.
Oh weird.. they do now show in EDIT but it's like it takes 2 scrolls. it appears to scroll to the end and then i scroll again and they are there. weird.

Trainer fields are present, as previously confirmed.
Client fields are present in TEAM. and populating.
OK. closing!
