### ISSUE TITLE
look at having Teams drive last* dates for client and dog records

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#405]
ideally want to have access to all "last*" dates on client and dog records in Teams.
It would possibly make the most sense to set them on the team and have a trigger to copy them to contact.

contemplate best way to do this.

**Comment by atlasjen** [comment]
I spoke with Niki and Molly.
Here is the thought, and this aligns with #404 and #395 and #400 in consolidating data to teams.
use case flow is going to likely be
- someone (programmatic or manual) creates a contact. From there they create a team (which has the step of creating a dog along the way)
- As files come in that are needed to apply, those all get added to the team, be they for the client or dog.
- when it comes to client annual recerts forms those get set on the team (PATs are already on the team)
- when it comes to dog vaccinations, those stay w the dog. we have all of that fancy logic there.
- I am envisioning an LWC on the related tab of Team that has these Last* dates set by uploading files in the related files component in teams (see #400)

From the contact side, here is what i think moves to being set in the team and needs to be displayed in the team
![image](https://user-images.githubusercontent.com/66139437/207483241-25eb8df9-1af3-43d5-9d65-839f206de424.png)

If it has a "C" it stays on the contact side and is just associated w the contact, not a team
If it has a "T" it isn't displayed on the contact at all. It really should be a new team field and we deprecate these
If it has a T->C, it is set on the team but displayed in the contact.

From the Dog side, here is what i think moves to being set in the team and needs to be displayed in the team
 
![image](https://user-images.githubusercontent.com/66139437/207483707-94bb3a93-f656-423d-9ec3-58468ad48f7a.png)

If it has  a "T->D" it is set on the team and copied to the dog
If it has a "D" it is just on the dog. all of the other stuff on dog is just on the dog.

- Some considerations. IF someone edits data on a team, it should stomp on whatever is on the contact or dog.
- People will still upload some files to Contact and some to Dog. but we will use business process to say what gets uploaded where.
- Ideally we would have (info) little icons by any field that is set by a trigger to say don't touch. This also includes the Team PAT Valid Until which is set from the PAT

**Comment by deb761** [comment]
I could put a form to update the client and dog data in the team details, or do you also need the status in the Team?  Alternatively, we could have a form in the client that sets the team fields.

**Comment by atlasjen** [comment]
I think we set status on the team and it pushes to client and dog. I need to be able to have status on teams.

**Comment by deb761** [comment]
Sorry, I was referring to the Last* dates.  It's bad enough that we need to have those fields, but having duplicates of them hurts.

**Comment by atlasjen** [comment]
I think we said we can remove them from contact so they’d just be w the team .
So pat date would drive last certified date on team. The various client files last* dates would be on team

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by deb761** [comment]
Team change trigger: Copy status & Cert Valid Until to client if Team is not 'Decertified or Discontinued'
Dog last dates stay on dog object, and are updated using the CDL trigger.  Can also add CDL to all dog teams.
CV trigger adds CDL to Client or Dog.  CDL triggers cause last dates for Dog.

**Comment by atlasjen** [comment]
These dates are not showing in Teams in staging

**Comment by deb761** [comment]
Updated Teams layout.
