### ISSUE TITLE
Add helptext to help avoid confusion on workflow

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#428]
I'd like to add the following tooltips/helptext to help ensure people follow the proper workflow w teams.
I can also do this directly in prod. Not sure if this is managed as part of the package or not.  If it isn't part of what comes in the package, let me know and i'll just do manually.

**Contact**
- Client Status "Derived from Team. Do not edit directly"
- Client Certification Valid Until "Derived from Team PAT. Do not edit directly"
- Positions "Be sure to specify positions you wish to see details for on the contact. Position detail will not be shown if positions are not selected first"
-for all of the last* dates that are set automatically "Set at the time of file upload. Do not edit directly"
-Last Contact Form "Set programmatically when online contact form is completed"
-Mailing Address "Edit the account address vs the Contact address unless you intentionally want them different"

**Dog**
- Dog Status "Derived from Team. Do not edit directly"
-for all of the last* dates that are set automatically "Set at the time of file upload. Do not edit directly"

**Team**
- Status "This status defines the status for the Team, Dog and Client"
- Passing PAT Count "This field must be set manually"
- PAT Valid Until "Derived from most recent passed PAT. Do not edit directly"
-for all of the last* dates that are set automatically "Set at the time of file upload. Do not edit directly"

**Comment by atlasjen** [comment]
these are not showing in staging. do they need to be manually added to staging/prod?

**Comment by deb761** [comment]
I guess so.  I am not adding them to Staging.  I am not happy with how Salesforce does this.

**Comment by atlasjen** [comment]
ok. let's just add them to prod. agreed. annoying.
