### ISSUE TITLE
Add "dog" as a column in TF and Client logs

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#430]
I am not sure if this is something we do here or in prod, but i want "dog" to also display as a column when we look at TF or client logs. Right now it does not. This should be included pretty early in the columns so it is right after the client and handler names. This would apply to viewing it under contact or team.

Right now our "team" filtering on logs just seems to filter on client, not also dog and we don't have any logic that forces logs to be related to valid teams. As a first step, let's include the dog name on display. it is a later issue (diff release) to address the logic differently.

**Comment by deb761** [comment]
The current log lists are the same as what you get for the client record page, since we don't know who the facilitators are in the team definition.

I suggest we modify these related lists to include records for the client where the dog is the dog in the team.  That's about the same amount of work as adding a column that's filtered. 

These logs come in through your Forms app, right?

**Comment by atlasjen** [comment]
They don't come in through form assembly yet, but will.

so if a client is in 2 teams, would files for both come through? i would think it should still have a column that shows us the dog name, but yes, not filtered by it.

Agree, preference would be to only show ones in teams.

**Comment by deb761** [comment]
I’m working an idea of adding an AND for the dog Id. I would have more work for the view all, but making progress.  Sent from my iPhoneOn Feb 14, 2023, at 1:31 PM, atlasjen ***@***.***> wrote:﻿
They don't come in through form assembly yet, but will.
so if a client is in 2 teams, would files for both come through? i would think it should still have a column that shows us the dog name, but yes, not filtered by it.
Agree, preference would be to only show ones in teams.
