### ISSUE TITLE
add "age" as a derived field in contact

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#435]
We need to answer questions on age of clients and it would be easier to have "age" as a derived field based on birthdate on contact.
it would be set whenever birthdate was updated on contact.

**Comment by atlasjen** [comment]
Lets go with it the same way you have for dog.
And then yeah, if you are game to fit this in this release (1.4) that would be cool

**Comment by atlasjen** [comment]
Oh let’s have it by birthday.

**Comment by atlasjen** [comment]
need to add to page layout in staging/prod

**Comment by deb761** [comment]
Updated layout and One Note

**Comment by atlasjen** [comment]
confirmed. closing.
