### ISSUE TITLE
need to make background check needed status available outside of when volunteer status active

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#438]
I was updating some reports on background checks last night and realized now that fields are only displayed if a position is specified and a status is set for that position, we no longer have access to how we were specifying is someone needs a background check in 1.4 so we need to fix that.

Presently we use the Volunteer Access field under Volunteer Details
![image](https://user-images.githubusercontent.com/66139437/221911866-87d8a405-6e94-4f56-9a07-119cdc3177a3.png)

This is used for volunteers, board members and team facilitators. If someone is a TF but doesn't volunteer in other ways, we specifically don't use the volunteer position. Same for the board folks. It helps us see who is who.

I don't think we have any logic in the system presently based on these volunteer access fields being set so the only thing this change breaks is my reports.

Some options I can see. Open to ideas.

1- we add  "background check required" and  "credit check required" as checkboxes up in the main section and pull these 2 items out of Volunteer Access
2- We move "Volunteer Access" up to the main section and rename it to "System Access"  <- this is my preferred
![image](https://user-images.githubusercontent.com/66139437/221913516-880348fb-1c2f-41bb-bde2-5034c33cf8e1.png)
3- we change the logic for when to display the volunteer related section to also be if Team Facilitator, Team Facilitator Lead or Board are selected positions

The reason i like option 2 the best is 
1- no code changes for you I hope
2- board members have varying access to locations, so that field would also be helpful to see for board members not just volunteers
3- simplifies my report fixes too

**Comment by atlasjen** [comment]
Need to add to the page layout in staging/prod

**Comment by deb761** [comment]
It's there, just under Positions.

**Comment by atlasjen** [comment]
AhI I see it now
