### ISSUE TITLE
Team Status not properly set in munge for 1.4

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#442]
I am seeing cases where Team Status is empty (and client and dog is now too)
For example on my user, Jennifer Kolar, all statuses are empty
https://atlasassistancedogs.lightning.force.com/lightning/r/Contact/0034x00001COhAUAA1/view
The Dog Health status also shows NA, this is likely due to dog status being empty.

Let me know if this is an easy munge for you. If not, it's not too hard for us to manually fix.

**Comment by deb761** [comment]
We have no triggers that set Team Status.  And Team Status is new for 1.4, so I would expect it to be empty.  Since I don't have the rules for Team status, please go through and set this manually.  We have a trigger that updates the Client and Dog status when team status is set.

**Comment by atlasjen** [comment]
OK will do.
