### ISSUE TITLE
we should include Status columns on Teams and Dogs under Contact

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#444]
Now that everything is team centric, i would say we should include the status column on Related Teams and Related dogs under contact.
Look under Ellen Martin https://atlasassistancedogs.lightning.force.com/lightning/r/Contact/0034x00001FPqJ7AAL/view
There is no way to tell that the active Team is EllenMartin_Codi or the active dog is Codi.
Much like Relationships has a status, can you include the status in these two related components?
If we need to make this 1.5, we can live w/ it. Let me know.

**Comment by deb761** [comment]
Related dogs is just a layout change.  Related teams is a LWC change, so needs to be 1.5.

**Comment by atlasjen** [comment]
I was just thinking it was display the Dog.status and Team.status in the current related list, so a config change to add 1 more column to the view.. but if that is a LWC change all good to move to 1.5. moving it.

**Comment by atlasjen** [comment]
In Staging, I do see the column under the Team, but not under Dog.

**Comment by deb761** [comment]
Added to Contact layout and updated One Note

**Comment by atlasjen** [comment]
verified in staging.
