### ISSUE TITLE
dates for Last Trainer Prof Ref Letter and Last Trainer Client Ref Letter are empty

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#445]
Do we still have access to the data that had Last Trainer Reference letter date?
The dates for our new fields are empty
- Last Trainer Prof Ref
- Last Trainer Client Ref
It looks like the files are all still there and classified as Trainer Reference Letter.
I'd say we pull whatever the latest date on any of them is and set it for both fields.
Fine to leave the category on the file upload as is.

This is a lot trickier to do manually and impacts a lot for fields than team status, so hopefully you can do this as a munge.

**Comment by deb761** [comment]
I've tried running scripts to update these letters, but am not getting anywhere.  I'm been manually updating the document type on trainer reference letters, and that does update the document dates as expected.

**Comment by atlasjen** [comment]
ok well that sucks. then i will get it taken care of on my end if it is manual. no need to waste your time on that.
