### ISSUE TITLE
Valid until not shown in PAT related list in Teams (1.4 prod release)

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#446]
Can we add showing the valid until column in the related PATs under team?
I realize now this isn't in staging. If this needs to wait until 1.5 it can, but if it can be patched in 1.4 it is def preferred

<img width="746" alt="image" src="https://user-images.githubusercontent.com/66139437/226361918-21ff6edb-991c-4317-aa23-9b17b49b4459.png">

**Comment by deb761** [comment]
This will need to go to 1.5, since its in a LWC.
