### ISSUE TITLE
can't change Valid Until on a passed PAT w/o changing status away from Passed first

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#461]
in 1.4 release
I went to correct the date on a PAT that had been submitted as passed.
The Valid Until box is not displayed for edit
![image](https://user-images.githubusercontent.com/66139437/232168470-65e63eb6-064d-4b0a-9670-7d71707ca629.png)

If i save as a different status type, and then change back to  passed, then i can edit it. I don't appear to have to save in between. minor nit.

![image](https://user-images.githubusercontent.com/66139437/232168536-028ea401-e01e-4ccb-b5ad-6250c66e7b44.png)

**Comment by atlasjen** [comment]
cant repro in prod.

**Comment by atlasjen** [comment]
I just reproduced this in staging. Go to team PeggyDunner_Jojo
you will find 2 pats. The Valid Until field is not displayed when I go to edit.
![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/8c29cb41-8b93-4e35-90d9-d974edcd2e1b)

**Comment by deb761** [comment]
I'm not sure why this logic isn't working properly in orgs using the package.  Do you want to wait for me to figure it out (and I don't even have a WAG on the time required), or go ahead with 1.5 after I fix the bug with no category/field on the file upload dialog.

**Comment by atlasjen** [comment]
We have an easy work around on this, so let’s move forward w/o this on 1.5 if it is a big wormhole.

**Comment by atlasjen** [comment]
moving to 1.6 release. work around is to change status away from passed and back.

**Comment by atlasjen** [comment]
Closing. I can't repro in sandbox or prod.
