### ISSUE TITLE
Add triggers for Valid until on TF and Trainer

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#464]
Change "Trainer Certification Valid Until" to be 1 year from "Last Trainer Program Agreement"
Change "Facilitator Certification Valid Until" to be 1 year from "Last Facilitator Certification Agreement"

**Comment by deb761** [comment]
Those two fields are already formula fields.

**Comment by atlasjen** [comment]
adding note that this was properly implemented as I intended vs what i wrote above. Trainer Cert Valid until is based on Trainer Cert Agreement Date.
