### ISSUE TITLE
Add new Field "Last Board Term Start Date"

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#465]
This is a date. put it under Board Specific Details.

Then, we can add a trigger that sets Board Term Valid Until to be +3 years + however long to June 30th of that year.

so if the last board term start date = June 30, 2021 --> valid until June 30, 2024.
if last board term start date = May 1, 2021 --> valid until June 30, 2024
if last board term start date = Aug 4, 2021 -->valid until June 30, 2025

Then add help test on Board Term Valid Until that says it is derived.

**Comment by atlasjen** [comment]
reopening. can't see in staging.

**Comment by deb761** [comment]
Added directions in One Note

**Comment by atlasjen** [comment]
verified in staging
