### ISSUE TITLE
Staging- files uploaded to Team not showing in Dog or Contact

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#478]
This is in staging
with the change to label file types as Team Dog and Team Client, they are no longer being copied to the contact/dog to be viewable there.

**Comment by deb761** [comment]
We need to turn on a custom setting.  Documented in One Note.

**Comment by atlasjen** [comment]
Verified in staging for newly uploaded files. In prod we will need to make sure that the proper things get reclassified as TeamClient and TeamDog when displayed in the client and dog related lists.
