### ISSUE TITLE
Add ability to hide file type based on permissions

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#483]
related to #482 , we need a way to limit which files a user sees. In particular, it would be files for Client,ADSiM and TSiM that I would want to hide.

We are going to be creating a public group like "VolunteerAccessOnly" , so if the LWC could access that , that is one simple approach. 
we could just show files that have no type or have type volunteer.  We will also be making a public group for people who can access everything. "FullAccess" .

overtime i could see filtering by other groups, but right now this would meet our most important use case.

perhaps this can be another column in the mapping we already use to say which categories and types go together. it could just contain  the name of the public groups that have access..

**Comment by deb761** [comment]
I would suggest naming groups based on the access granted by the group.  So:

- Everyone can access files with no category
- VolunteerAccess can access Volunteer category files
- FullAccess can access all category files

**Comment by atlasjen** [comment]
that makes sense.  i know the ones that ADI (assistance dogs international) will be most concerned w us protecting are client records.. so I wonder about FullAccessNoClient as another option just to say we have it.. however, that's not a valid use case right now so maybe we dont' make it more complex than it is?

So is this something you are able to access from the LWC?

**Comment by deb761** [comment]
Each object in Salesforce has an owner.  This owner can be a group, so if we set the owner of each file to be a group, we get the filtering for free.  I think.  I am testing that theory now.

**Comment by atlasjen** [comment]
reopening in 1.8

**Comment by atlasjen** [comment]
i think we can close this, ya?

**Comment by atlasjen** [comment]
closing as fixed in 1.9
