### ISSUE TITLE
Add "Standalone" as a position

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#485]
Right now it is really hard to tell who is active in something or not in a way we can do bulk emails.
Rather than having the position be blank, let's add "Standalone" or "Standalone Student".

This would cover any of the standalone courses including TSiM. We are pushing these standalone courses more and more and we need a good way to access info about them in Contacts.

Statuses would be similar to trainer and others: [Standalone Status]
Initial Inquiry
Onboarding
In Training
Inactive
On Hold
Discontinued
None

For the File upload component, we already have Standalone Programs as a category and we already have these two file types. so no change there other than setting the last* dates.
- Application
- Program Agreement

For the Standalone position details we would have these set based on the file uploads.
- Last Standalone Application
- Last Standalone Program Agreement

Then there are these related updates (not sure if i missed any)

- add Contact.IsStandalone and code to populate it
- update Category Rule to add Standalone as a position for Contact
- update code to display some sort of icon in the Position(s) with Status detail pane

We can do an import after the fact to set standalone status, and position as needed. I can manage that.

Are you able to programmatically backfill the dates for the standalone application and agreements based on what has been uploaded to files?

**Comment by deb761** [comment]
Yes, I can update the post-install scripts to set the dates.
For positions with status, I am taking the Standalone status rather that checking the program assignments.

**Comment by atlasjen** [comment]
Opening to track what may be code changes or may be post package deploy configuration. Testing in Beta11.
1-  what has to happen to make the standalone position details section show?
2- now that i've added standalone manually as a position, when i go to look at the file upload options, I see some of the categories appear twice. and i am not seeing all of the positions as category. for example, here are the positions for this user:
https://atlasassistancedogs--beta11.sandbox.lightning.force.com/lightning/r/Contact/003E200000GSZTDIA5/view

![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/9337e325-b383-4ea6-896d-4d9240c6ada2)

But here is what i see for file upload.
![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/8f50a8fa-eb61-48f4-add5-abaca2116c1e)

I tried a case where the only position was Standalone and "standalone" appears 2x..
and actually, now ANY file upload I go to , regardless of position options seems to just give me these two category types. I am not sure if there is some inconsistent permission that is confusing the code. That is my hunch.. but not sure what else to change.

I added the category rule for standalone, in case that was the issue, and now then i go to the file upload i see 3 listings for standalone 
![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/8fb00e06-8e96-451b-8aca-eca5efecdb57)

I deleted the other positions, and now i see 3 standalone options. 
Now if i add back in positions, i get duplicates of the categories, but I am still missing some. for example, i am missing team facilitator and client. I wasn't seeing any of these kinds of weird inconsistencies before I added "Standalone" as a picklist position.
![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/61e9b139-25db-4091-be1f-769e3b844804)

![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/5c377920-f5d3-4143-bbac-9ee389f596fc)

**Comment by deb761** [comment]
I found the problem in beta11: the Category Rules had been duplicated.  Removing the duplicate records solved the problem.

**Comment by atlasjen** [comment]
testing in beta12. category rules look correct. When i add standalone as a position, it properly shows in related. However, i have no ability to upload that as a file type. likely related to other open fileupload item #514

**Comment by atlasjen** [comment]
In beta12, i see the standalone categories properly again, but i am also seeing Assistance Dogs Set in Motion which i thought we removed unless the position included client.. but i honestly don't recall at this point.

**Comment by atlasjen** [comment]
however, relative to standalone.. i think we are good.

**Comment by deb761** [comment]
ADSiM is not tied to a position, but is only visible if you are in the Teams group.  It is configurable, though.
