### ISSUE TITLE
change how board term valid until is calculated

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#486]
We have changed it so we can onboard board members at any monthly meeting.
I realized our present logic uses june 30th 3 years after whenever the last agreement was.
We want to now have it be the last day of the month 3 years from "Last Board Term Start Date"

so , for example, if they started 2/23/2023, the term would be valid until 2/28/2026.
I tried manually changing these but the logic overwrites it.

**Comment by atlasjen** [comment]
testing in beta11, from what i can see it is still going to june vs april (see detail in pull request) where we discussed this.
https://github.com/Atlas-Assistance-Dogs/atlas-dogs/pull/496

**Comment by atlasjen** [comment]
i was just testing in beta 11 and got this error when i edited the last board term start date
![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/360dbea7-e133-47f0-83a9-8fd50bceba1c)

**Comment by atlasjen** [comment]
Also related. if i add board as a new position, it automatically populates two dates. i would expect these to be blank.
![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/b0378262-7094-4b38-8f3f-6a1548d0ea93)

**Comment by atlasjen** [comment]
just tried setting this in beta 12, still getting the same error.

![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/dadbd1a1-c6cf-45e7-a3ef-eed1ec8c9286)

**Comment by atlasjen** [comment]
works!

**Comment by atlasjen** [comment]
where do i find "atlas settings"?

**Comment by deb761** [comment]
Settings > Custom Settings > Atlas Settings
