### ISSUE TITLE
Add addl date on Team

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#497]
We need a good way to report when Team Training actually starts which can be pretty different than their agreement date or date the program was assigned. 

Let's add "Training Start Date". it will be manually set. Let's put it in the page layout where this red box is.
![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/9a9733ab-6b5d-4233-b83d-3c50b5e6f844)

**Comment by mguillendev** [comment]
I can do this quickly from the Salesforce org. Can I do it directly in production or do I have to do it first in some test org? in either case, could you send me the link to the org? I understand my user is mariag@atlasdog.org, is that correct?

**Comment by deb761** [comment]
Create a branch off of dev in the repository.  You can do this in the issue in GitHub.  Check out your new branch, make your changes in the org, then “sf project retrieve start” to pull the changes down.

See the Trailhead

**Comment by atlasjen** [comment]
re-opening. this is missing in beta12.

**Comment by atlasjen** [comment]
confirming this is in beta14

**Comment by atlasjen** [comment]
confirming in staging
