### ISSUE TITLE
added "pending" to status picklist on Relationship object 

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#507]
Just documenting that i changed this is prod so it would be good to add in this next package formally.

![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/0c85a5d1-ec21-4a4d-8079-a42e09a28735)

**Comment by deb761** [comment]
Since it's not involved in any logic, and it involves a custom field from another package, I suggest we leave it out of our package.
