### ISSUE TITLE
Last Facilitator Certification Date doesn't update if it is to an earlier date (or deleted)

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#508]
I believe the issue is

1) if a file is removed the Last * Date isn't cleared or rolled back to the previous last date
2) if a file's date is updated that was older than the previous last *date, the last* date isn't updated.
-----------------------------
Here is the use case.
This is on Madeline Jill Mohr's record in prod. (release 1.5)

Laura accidentally uploaded a Trainer Certification document and used the Team Facilitator type.
It had a date of 12/12/23.

There previously had been a Facilitator Certification document w/ the Team Facilitator type.. It had a date of 7/25/23.
![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/0f666d77-7159-4b45-be22-1cde72e9deb8)

As a result the Last Facilitator Certification Agreement date was stomped on and changed to 12/12/23. That is expected proper behavior.

To attempt to fix this, I had her:
1) change the type on the most recent team facilitator one to trainer and save. That fixed the last trainer certification date.
2) try to change the date on the other team facilitator one by a day or so and save to see if it would trigger an update to the Last Facilitator Date. It changes the document date that is shown in the related file list, but the Last Facilitator Certification Agreeement date isn't changing.

![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/1968faee-7136-4d63-bdca-8605520c8c19)

![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/5d7eb4f1-28e7-49f0-83ff-7c2aa0dd918b)

She also tried deleting the Team Facilitator Agreement.
That means, the date should have rolled back to the most recent one there
![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/3a3407d9-e723-4af1-a518-dc2700a32810)

However, when i go look at position details (after refresh), this is what i see (it didn't clear the date or reset it)
![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/9837ae8d-6abf-46ad-b686-7ea38b83ff99)

I then upload the doc again but nothing changes in related.

**Comment by deb761** [comment]
I'm concerned that any fix would wind up pushing the trigger over the SQL query limit.  I'll try it out, but why didn't you tell her to just set the correct date in the Last Facilitator Certification Agreement field?

**Comment by atlasjen** [comment]
I will have her do that but for now left it so you could see the issue.

**Comment by atlasjen** [comment]
what did we decide to do with this?

**Comment by deb761** [comment]
Update the date manually in these situations, as the trigger solution is too query intensive.

**Comment by atlasjen** [comment]
ok. closing.
