### ISSUE TITLE
Related contact is still shared when Position removed

### ISSUE THREAD

**Issue by deb761** [Atlas-Assistance-Dogs/atlas-dogs#512]
1. Set up sharing rules for contact so that ShareWithVolunteer is visible to users in the Volunteer Group.
2. Add Volunteer position to a contact.
3. Add Primary and Secondary emergency contacts to the original contact.
4. Observe that all three contacts are visible to a user in the Volunteer group.
5. Remove Volunteer from the original contact.
6. Actual: Primary and Secondary emergency contacts are still visible to a user in the Volunteer group.
7. Expected: Primary and Secondary emergency contacts are not visible to a user in the Volunteer group.

**Comment by deb761** [comment]
This has been fixed in 1.6.

**Comment by atlasjen** [comment]
testing in beta12. i added a related contact to a Volunteer as a full user. I then logged in as Peony Ho (volunteer user) and while i can see the relationshp 
![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/055cdebb-9e5a-40b5-9833-0d5323f33b77)
nubmer, and type, i can't see the related contact (not a volunteer)
![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/9ad1d2bb-473c-487f-84ce-3c0bfb44f27e)

I can see all accounts, but can't see any contacts other than this one
![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/071ca95c-8a61-4f1e-88ee-75053a141263)
There is also no data visible in Programs or Program Assignments when i am in  as this user

**Comment by deb761** [comment]
The Volunteer can only see related contacts that are Primary or Secondary Emergency Contacts, so that makes sense, even though it looks funny.

I had to re-create the Atlas Volunteer permission set because it includes permissions from another package or something like that, and had neglected to add Programs and Program Assignments to it.
I also ran a PostInstall method to set the fields that allow sharing on the volunteers and related contacts.  I'll add it script.

**Comment by atlasjen** [comment]
OK. verified. I can indeed see them not that they are primary or secondary.

**Comment by atlasjen** [comment]
also verified once relationship type is changed, the contact is no longer there. the relationship is, but i don't think that hurts much.

**Comment by atlasjen** [comment]
i htink we can close this, ya?

**Comment by atlasjen** [comment]
closing w 1.9
