### ISSUE TITLE
File upload not displaying the proper categories in beta11 or 12

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#514]
The file upload is not showing all possible categories . this is as of 2/20/24 in the beta11 sandbox.
For example, Ortiz Kylie only have Trainer and Volunteer as category options.
He should also have Client, Team Facilitator and Standalone as well as NA
![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/9d539406-fb1f-48a0-9298-034bb61cd010)

I tested a few other folks. Similar oddities. I haven't been able to figure out a pattern yet. I tried tweaking statuses for the positions, but that didn't resolve it. 
Anthony Liu doesn't show any category options

![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/60056996-5c66-4e5e-aacd-ad1bf66f981e)

**Comment by atlasjen** [comment]
I realized Client shouldn't be showing as that is just teamclient.. but the others should still be showing.
I wonder if this is related to permissions? let me know when you have a chance to look at this. once this is resolved i can start testing various types of "users" w differnt permissions.. still working w this w me as a user w all new permissions.

**Comment by deb761** [comment]
Fixed!
<img width="2488" alt="image" src="https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/9601218/9808ea36-448b-4dc8-89ca-555da83994c4">

**Comment by atlasjen** [comment]
testing in beta11. 2/26 and comparing to production.
Progress. I am seeing more category types :)

1. I don't think we should see "Team Client" as a option for file types to upload under contact if someone is a client? aren't those only uploaded under the Team?

![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/d9a0d8a5-ffa3-40c7-95a7-c2248d57c3b2)

2. Remind me about Assistance Dogs Set in Motion files.. i guess those aren't a position, so we left them for everyone, is that right? Pretty sure that is how we have it in prod. we might want to change this but can punt on it for later.

![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/03c4506b-faff-4a35-810e-824246343d5f)

3. I am no longer seeing "N/A" as  a category option. (look in examples above) In prod, we could pick N/A and then a type of "Contact Form" or no type. That said, i can upload a file w/o a category or type, so maybe that makes more sense than the NA. Curious of the intended change here. I am also no longer seeing "standalone" as a type for everyone, which is good.. so again, the NA may be intentional and i am cool w it.. just double checking. In that case i think we'd want to move Contact Form under each type vs having it under NA, so if we did save a contact form, we have something to specify. I am curious what logic impacts the "Last Contact Form" date now.

4. Puppy Raiser isn't showing as a possible file type even if it is a position. The others all do appear.
![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/85f6d8fc-c731-477d-b01e-a598bd9724c2)

5. If someone is a Team Facilitator and Team Facilitator Lead, Team Facilitator is present twice as a category type. Note, this is also true in prod i just realized.
![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/d1e3bed8-a211-4824-8b94-aab2418fa1e5)

**Comment by atlasjen** [comment]
For this release we are accepting
- NA and ADSiM show for all
- Team Client shows as possible to upload in Contact 
We will split up the rules for what can be uploaded and what can be viewed in next release.

**Comment by atlasjen** [comment]
testing in beta12, i added Team Facilitator as a status to someone who already had Team Facilitator Lead. I have refreshed a few times, but i only see "NA" as a file upload option.
![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/ee6716c2-19f2-4a8b-9901-6b5916e0ce77)

**Comment by atlasjen** [comment]
I tried adding client and same issue.

**Comment by deb761** [comment]
I had forgotten to add you, Molly, and Laura to the "All" group.  You should see it now.

**Comment by atlasjen** [comment]
Ok. yep, working as expected. closing.
