### ISSUE TITLE
Add tracking of 1st aid training

### ISSUE THREAD

**Issue by deb761** [Atlas-Assistance-Dogs/atlas-dogs#515]
Add First Aid Certificate to ContentVersion document types, and tie to Staff and Team Facilitator categories.
Add LastStaffFirstAid and LastFacilitatorFirstAid fields to contact and set them to the file date.

**Comment by atlasjen** [comment]
change from "First Aid Certificate" to "First Aid Documentation" for file type.
leave on staff and TF

**Comment by atlasjen** [comment]
So.. it occurs to me we should likely change to FirstAidCertificationValidUntil.. the current program i am looking at is good for 2 years.

**Comment by deb761** [comment]
In that case, we would have to add another derived field.  Or, since you only have a few people you use this on, wait for the next version for the field, or add it after the package....

**Comment by atlasjen** [comment]
yep. let's wait for the next version. we can use this as is for this.

**Comment by deb761** [comment]
Closing and working #545 to complete.
