### ISSUE TITLE
Beta12 & Staging: Standalone details showing even if there is no standalone position

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#523]
In Beta12, i am seeing Standalone Details appear for all users even if that position is not set.

**Comment by deb761** [comment]
I missed a step when setting up the org.  Fixed now.

**Comment by atlasjen** [comment]
OK. fixed indeed.

**Comment by atlasjen** [comment]
In staging, I am seeing Standalone as a file option even though standalone is not a position for this person. Only position they have is Client.

![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/9125b289-b0ea-48dc-894d-b18d856f7432)

**Comment by deb761** [comment]
Fixed.  Deleted duplicate Standalone Category Rule.

**Comment by atlasjen** [comment]
agreed. fixed now.
