### ISSUE TITLE
Beta12 & staging: permissions on admin (Jen) don't allow deleting relationships (but can create them)

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#524]
As Jen, i went to delete a related contact, in particular, the Bryan King contact on Cook Megan.
Here is the error I got:

![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/40aab9c3-2550-45c9-a6ab-498d46828ea6)

**Comment by atlasjen** [comment]
Tested that I can create but then not delete.
Can also edit.
Debbie's user also cannot delete.

**Comment by atlasjen** [comment]
@mguillendev  Do you have any ideas on what might be going on?
- in the beta12 sandbox we have changed the sharing settings for Contacts to private
- we have then defined sharing roles to allow non owners to read/write contacts
- the sharing rules for relationships is "Controlled by Parent" and we can't seem to edit it. it might have to do w/ being an NPSP field.

we aren't seeing this issue w/ other non NPSP objects- we can add/remove files, program assignments, background checks, etc. (assuming sharing rules allow those objects)

**Comment by atlasjen** [comment]
Beta 14:
I went to create a new relationship and a new contact.
I was working on contact "Darius Fritz" as that is the only contact there.
I created a new contact but didn't give it a type.

![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/55687207-c3e2-472b-b9e1-78d2d2855b55)

I then gave it a type and it successfully created.

**Comment by atlasjen** [comment]
I then tested deleting that related contact and I am still seeing permission issues
![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/3520cd6f-1ef5-42f6-a286-da7bb72da500)

**Comment by atlasjen** [comment]
this is still a problem on staging. 
![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/1a839a19-5c39-4e9f-bfe6-dfd99a4b5193)

**Comment by deb761** [comment]
This one will need Salesforce support.

**Comment by deb761** [comment]
Closing with linked PR.
