### ISSUE TITLE
Beta 12: Volunteer role doens't have permission to upload volunteer files

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#525]
In Beta 12, I am logged in as Peony Ho.
I went to upload a volunteer file and got this error.
I assume it is permission based.

![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/007971d6-8041-4e39-8337-0b67d96dfdd1)

**Comment by atlasjen** [comment]
I also tried w/ category on N/A and same result.

**Comment by deb761** [comment]
It's more likely we've hit the limit on files for the sandbox.  Try deleting a few you've uploaded.

**Comment by atlasjen** [comment]
changed sharing permissions on Contact to allow read/write for Volunteer (and team).

**Comment by atlasjen** [comment]
moving to 1.8 and reopening

**Comment by deb761** [comment]
View all problem should have been fixed with 1.8.

**Comment by atlasjen** [comment]
view all yes. this was about volunteer permissions.

**Comment by atlasjen** [comment]
closing as fixed with 1.9
