### ISSUE TITLE
background checks need to be restricted much like demographics

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#527]
In beta 12: it looks like the volunteer user can still add a see background checks.
They shouldn't be able to. 
Ideally they would have their own restriction category, much like demographics does.
For this release, we could lump the two together and just use the demographic public group and remove background checks from it.

thoughts?

**Comment by deb761** [comment]
The volunteer permission set is completely out of the package, so it can be set up however is needed in the org. Heck, is any of the permission sets I put in the package don’t work, you can clone and tweak them. We’re probably putting too much config stuff in the package as it is. Sent from my iPhoneOn Mar 27, 2024, at 11:51 AM, atlasjen ***@***.***> wrote:﻿
In beta 12: it looks like the volunteer user can still add a see background checks.
They shouldn't be able to.
Ideally they would have their own restriction category, much like demographics does.
For this release, we could lump the two together and just use the demographic public group and remove background checks from it.
thoughts?

**Comment by atlasjen** [comment]
so what part is controlled by the public group vs the permission set?
I'm thinking a case where i might want to let people access everything but background checks and demographic info.. or evenything but background checks..   So i wasn't sure if we needed a diff public group.

**Comment by deb761** [comment]
The public group controls which records are available.  We've only put that sharing in Contacts so far.
The permission set controls which objects and fields are available.

**Comment by atlasjen** [comment]
Edited Volunteer Permission Set
- removed access to Background check. this resolves it.

**Comment by atlasjen** [comment]
beta 14:
i added teh backgroundcheck permission set to user Peony.
I logged in as her.
I correctly can see related background checks and the background check tab.
However, when i go to a contact that has a background check (Stuart Michael) and click on "view all" for related background checks, i get an error:
![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/7b2b3879-2021-4318-872a-706d8c52eff9)

 I also have no way to actually click to open to view the background check from the related tab on my contact, other than choosing edit.

![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/e579c90c-dbc7-4144-8b9f-a0e995783b70)

I tried creating a new background check and i am unable to add a file, either by choosing Upload or by dragging it ontop of the Upload File button
![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/88b9e8a8-d45c-43bd-9edc-ad7d7d4d5195)

I was able to make a new background check as long as it didn't have an attachment.

**Comment by atlasjen** [comment]
update for Staging. I still have no way to open a background check from a contact related list.. other then to edit it. there is nothing to click on like a background check name.
I was able to make new background checks w/ attachments, so that part of this seems resolved.

**Comment by atlasjen** [comment]
i believe this is fixed, right? so we can close?

**Comment by atlasjen** [comment]
closing with 1.9
