### ISSUE TITLE
Add Permission Set for Demographics, remove them from Atlas Team

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#528]
much like background check is its own permission set, we need one for demographics.
then remove them from team

these are the fields to add to the demographic permission set
![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/b40ac50e-8a96-45d4-adf7-619390f7848e)

**Comment by atlasjen** [comment]
moving to 1.8 and reopening

**Comment by deb761** [comment]
Please let me know which permissions need to be moved where.  Remember that you can always override permission sets in production by cloning and modifying.

**Comment by atlasjen** [comment]
i think the issue was that the "team" permission set was the one that also controlled demographics vs having it be its own

**Comment by deb761** [comment]
They are split out in 1.7/1.8Sent from my iPhoneOn Jul 7, 2024, at 2:28 PM, atlasjen ***@***.***> wrote:﻿
i think the issue was that the "team" permission set was the one that also controlled demographics vs having it be its own

**Comment by atlasjen** [comment]
so can we close this as resolved?

**Comment by deb761** [comment]
Yes.  Closing.
