### ISSUE TITLE
in PR restore restrictions, can't upload files w/o category

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#537]
This works fine in prod. In this PR:

- upload a file w/o a category or type is successful, but not shown in the related files in the contact.
- can add a file w/ category N/A and no type w/o issue. Saw an error once but can't repro
 
related to #536

**Comment by deb761** [comment]
So, how do you want to handle files with no category when it comes to view access?

**Comment by atlasjen** [comment]
Good question. We either allow them wholesale or don’t. I’m inclined to allow them . let me look and see what some examples are
