### ISSUE TITLE
change "inactive" to "complete" in Standalone Status

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#540]
Standalone courses are a bit different in that people complete them and are done. it's not an ongoing certification. So can we add "Complete" as a status and set whatever was Inactive to that?

I know i can add statuses manually but i wasn't sure if you had icon logic that would break.

**Comment by deb761** [comment]
“Completed" status will get the same icon as "Certified-Active”, “Certified”, and “Active".

**Comment by atlasjen** [comment]
what does "inactive" get as a status?

**Comment by deb761** [comment]
Same as “On Hold”, “Suspended”, and “Discontinued”.

    get image() {
        switch (this.status) {
            case "Initial Inquiry":
            case "Prospective":
                return "standard:question_feed";
            case "Onboarding":
                return "standard:flow";
            case "In ADSiM":
            case "In Training":
            case "In Progress":
                return "standard:education";
            case "Certified-Active":
            case "Certified":
            case "Active":
            case "Completed":
                return "standard:task2";
            case "Action Needed Soon":
                return "custom:custom82";
            case "Action Needed":
                return "standard:actions_and_buttons";
            case "Inactive":
            case "On Hold": // retained to allow production transition
            case "Suspended":
            case "Discontinued":
                return "standard:waits";
            default:
                return "standard:empty";
        }

**Comment by atlasjen** [comment]
ok perfect. then i will just change the value for the picklist in prod and we can close this. I know picklists don't propegate anyway. i'll change in staging and prod
