### ISSUE TITLE
"volunteer" files added as volunteer in beta 2 not seen as admin user

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#541]
This is in beta2.
I changed to user Peony Ho.
I went to contact Lydia Eaton. https://atlasassistancedogs--beta2.sandbox.lightning.force.com/lightning/r/Contact/003U9000009Au5ZIAS/view
I added 2 files, one "N/A" one "Volunteer".
![image](https://github.com/user-attachments/assets/5af15b47-58c3-47e6-96e3-6cdcda45f89b)

I also added an emergency relationship and assigned a program assignment. All seems good.

I logged out as Peony and went to look at Lydia Eaton.
I see the N/A file, but not the Volunteer classified file.
![image](https://github.com/user-attachments/assets/96236795-bbb4-4ada-99ac-692937889e29)

I logged back in as Peony and the volunteer file is there.

**Comment by deb761** [comment]
I had forgotten to add your new user to the All group.  You should see it now.

**Comment by atlasjen** [comment]
yep i see it now :) 

So i tried soomething a bit sneaky-- as the volunteer user
- i edited Helen Mcneil and removed volunteer as a position. It gave me an error saying i didn't have permissions, which is good.
- i hit cancel, then rather than bringing me back to the page I got this message

![image](https://github.com/user-attachments/assets/4dffd953-3de3-4f09-affd-759afe838e87)

and now when i go to look for the record, i can't see it, so clearly the edit did happen:
![image](https://github.com/user-attachments/assets/525dbb0c-7103-41da-8663-af8fadf9fb36)

i logged in as me, Helen Mcneil is there, and indeed, Volunteer has been removed as a position
![image](https://github.com/user-attachments/assets/20e96882-d4cd-4dc4-b13f-563395851dd2)

trying to think of what we want. we want the volunteer user to be able to - add new volunteers, so they need permissions to add users and change position to add volunteer. We also want them to be able to change volunteer status. maybe we accept it as planned behavior? ideas?

**Comment by deb761** [comment]
I don't see a way around this behavior, really.  Now, if Peony had created the Contact, she should still see that contact even without the Volunteer position.

**Comment by atlasjen** [comment]
so should she be getting the error about deleting the position? If we accept it as allowed behavior, i would think we wouldn't want the error.. or is it a timing thing.. that she's allowed to delete it while it has "volunteer" there, but when the page goes to refresh after the delete action, it then errors out as she's now not allowed to see the page?

**Comment by atlasjen** [comment]
i think the timing case is exactly what is happening.. i tihnk we consider this a won't fix re the error when removing volunteer as a position.

AND i think with your lastest changes we just tested this is good.
