### ISSUE TITLE
Accounts show for all contacts when logged in as volunteer user (beta 2)

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#542]
This is in Beta2.
When logged in as Peony, i can see all accounts. Since Accounts have phone numbers and addresses, this is not great.
is there a way to also hide accounts/households for any contacts that are hidden?

For example, Alison Vazquez https://atlasassistancedogs--beta2.sandbox.lightning.force.com/lightning/r/Account/001U90000075J6vIAE/view
is not a "volunteer" yet i can see her address and phone number.
i can't see the contact record.

**Comment by deb761** [comment]
We can make Accounts private like Contacts are.  We could also add sharing rules like we did for Contacts.

**Comment by atlasjen** [comment]
this can be closed i believe.
