### ISSUE TITLE
Add field for FirstAidValidUntil

### ISSUE THREAD

**Issue by deb761** [Atlas-Assistance-Dogs/atlas-dogs#545]
Add a field to Contact for FirstAidValidUntil that is 2 years after FirstAidCertification.  This field will be for Staff and Facilitator positions, and would be added to the actions for Staff and Team Facilitator.

@atlasjen Question: Do you want 2 fields? or one field that is the later of the two certification dates?

Relates to #515.

**Comment by atlasjen** [comment]
**READ to the end 1st as this is a processing response where the answer changes :)**
**Initial response:**
i would say we do what we've done w a bunch of these
Initial first aid training date
first aid valid until date
and we would upload a file that would set the valid until to be 2 years after the most recent 1st aid training date.

So what gets weird.. and it's not that common of a case, so maybe we live with it- we need to document this for Staff AND all who work w/ clients. so for molly and laura, that means technically it should go under staff as well as facilitator... and were we to have an actual office w/ volunteers in it who came in contact w clients, they'd need it to... 

**2nd response:**
So, another option is do we just move it to N/A as a category like we have contact form and we have a file upload type of Human First Aid Certificate.

but then do we really want both dates?
do we then instead do Last Human First Aid Training much like we have Last Contact Form?
the present cert i am looking at is valid 2 years.. that could always change.. so maybe that is the most flexible?


I can take advantage of the System Access field where we already list background check required and credit check required to also list First Aid Training required and allow us to figure out who needs it.

thoughts?

**Comment by deb761** [comment]
1. I like the idea of putting FirstAidCert under N/A.
2.  I think we want both dates, with the second being derived.

**Comment by atlasjen** [comment]
this is being tested in Beta5.
I thought we were leaving the category for the 1st aid cert to "N/A".
In beta5, i was able to upload under Staff, but then i don't see anyhting in the lastFirstAid Cert or First Aid Valid Until date under staff or facilitator. I then uploaded under Facilitator, and same thing.

Check out "Charles Munoz" as a sample contact i tested on.
I believe it should be NA as the category it is associated with so it sets both.

**Comment by atlasjen** [comment]
i went and edited the Content Version object to change the field dependency logic to shift to NA from facilitator and staff/contractor. that fixed it.
Closing. just need to remember that step in staging/prod
