### ISSUE TITLE
Automate a quarterly reminder to Active TFs to submit CEUs

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#547]
Since we are automating emails to clients and TFs for logs, let's get this one too:

For all Facilitators with Active Status, we want to send a quarterly reminder to submit CEUs.
We can just do this the 1st day of each quarter.

Email would be

---

Subject: Please remember to submit your Atlas Team Facilitator CEUs

Dear `<preferred name>`

This is a quarterly reminder to log your continuing education units. While you can submit them anytime before you renew your certification, it is often easier to do things like this during the year so you can remember what you read, watched, participated in or listened to.

If you are looking for ideas of what to do for CEUs, look at the Facilitator Group in Canvas at the `<a href="https://atlasdogacademy.instructure.com/groups/114/pages/atlas-ceu-options">CEU resource page</a>`. Remember it is as simple as 1 hr of your time spent learning something related to the training you do with our clients = 1 CEU.

ADI requires that all Team Facilitators complete 10 CEU's during each the year, so thank you for making sure to meet this important requirement.

To submit CEUs, simply go to : 
**NOTE for Debbie: replace {stuff } with salesforce fields**
`<a href="https://atlasdog.tfaforms.net/4907434?tfa_2={firstname}&tfa_4={lastname}&tfa_88={email}"> https://atlasdog.tfaforms.net/4907434 </a>.`

If you have more than one CEU to add, just click the "Add CEU" link at the bottom of the form and you can add as many as you want in one submission.

Thank you for being a part of Atlas.

Atlas Assistance Dogs
info@atlasdog.org

**Comment by deb761** [comment]
So, we need to show CEUs for Team Facilitators as well as Trainers?

**Comment by atlasjen** [comment]
Yes. It's actually more important as the team facilitators are who work w/ our clients, so under Assistance dogs international, we must track CEUs. Tracking them for trainers is our own internal requirement. form is identical for both.  we are getting ready to automate the CEU form and then will be importing the backlog, so that's why they aren't populated yet
