### ISSUE TITLE
staging- volunteer user has access to a few fields it shouldn't

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#553]
when logged in as peony, i can see 
the following demographic section (expect to see none)
and Lead Facilitator Status, Client Status and Standalone Status fields at the bottom (expect to not see those)
![image](https://github.com/user-attachments/assets/b9f89494-fa6b-4407-b5df-96b86a21773c)

Volunteer also has access to standalone details and standalone files.
I took a contact (douglas copeland) and added all positions, and then tested volunteer role:
![image](https://github.com/user-attachments/assets/7c9bc790-54e6-421e-8f77-e272284ebecc)

![image](https://github.com/user-attachments/assets/fa8d8141-ab44-4b9e-9c9c-ff3186b30a3f)

**Comment by atlasjen** [comment]
I sanity checked what was in beta5.
The demographic info is not there and most of the other statuses are not there, but standalone status is still there, so i didn't catch that in beta5

**Comment by deb761** [comment]
Peony has the Team permission set at the moment.  I removed it and gave her volunteer again.

**Comment by deb761** [comment]
Atlas Base with Relationships had Race/Ethnicity, Client Status, Criminal Conviction, Lead Facilitator Status, Specified Ability Status, and Volunteer Focus.
