### ISSUE TITLE
Staging- Team permission set doesn't include dog 

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#554]
Tested some permission sets
- Background check does what is expected.
- Demographic does what is expected.
- Volunteer does what is expected other than the visible fields noted in #553 
- Tested the Team permission set.

It adds Client permissions, which is expected but it did not add dog permissions.
I get this error when i try to open the related dog.
![image](https://github.com/user-attachments/assets/6091c881-3893-4f04-bedb-9bae93264d6c)

I would expect Team to also include Client and Dog.

**Comment by atlasjen** [comment]
Team status also lets you see
Team Facilitator Details
![image](https://github.com/user-attachments/assets/7943dd18-2b9e-40f6-a912-ad2709af762e)

**Comment by atlasjen** [comment]
i didn't test all of the various other ones as well (like trainer or facilitator) but did check the ones who have all and that seems to be good.

**Comment by deb761** [comment]
Something else is going on.  Atlas Team gives access to Dog, log, ect:
<img width="2184" alt="image" src="https://github.com/user-attachments/assets/678a51c7-840a-4bdc-87ce-f81c03a6cc53">

And yes, I did include Team Facilitator permissions in the Team permission set.

**Comment by deb761** [comment]
The problem is the Puppy Log component, Team doesn't include PuppyRaiser.

**Comment by atlasjen** [comment]
Ah.. and the puppy logs go w/ the dog..  I'm fine w/ adding puppy raiser to team.

**Comment by deb761** [comment]
For now, make sure anyone with Team has Puppy Raiser permission set.  I'm looking into handling access to Dog with/out Puppy Raiser, much like we did with the related objects for contact that not everyone has access to.

**Comment by atlasjen** [comment]
yep that does indeed add in dogs!
