### ISSUE TITLE
Staging- Team permissions seem to add many other contacts

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#556]
I tried out changing the permission sets and public groups on Niki Becker in staging. My goal was to set her as someone who had the "team" permissions but not anything else.  I discovered this while testing out visibility of dog.

She is Advanced Standard User profile and then has these assignments:
![image](https://github.com/user-attachments/assets/43f55a79-2ba2-4520-ad6f-84a679f43086)
![image](https://github.com/user-attachments/assets/c03e7587-86e6-4f83-96fb-1605ff0ce293)
I removed her from the All public access group.

We still have two extraneous fields:
![image](https://github.com/user-attachments/assets/50db72f1-41ad-407b-a455-d33e6872c936)
 
And she can see a lot of contacts besides clients or facilitators
![image](https://github.com/user-attachments/assets/8bfd60fe-f0e5-489c-a62c-51e14f3df789)

I am likely not understanding the right combination of permissions to set, but wanted to confirm.

**Comment by deb761** [comment]
Advanced Standard User has view all on Contact. Remove that if you want those users to have limited access. Sent from my iPhoneOn Aug 8, 2024, at 9:49 AM, atlasjen ***@***.***> wrote:﻿
I tried out changing the permission sets and public groups on Niki Becker in staging. My goal was to set her as someone who had the "team" permissions but not anything else.  I discovered this while testing out visibility of dog.
She is Advanced Standard User profile and then has these assignments:
image.png (view on web)
image.png (view on web)
I removed her from the All public access group.
We still have two extraneous fields:
image.png (view on web)
And she can see a lot of contacts besides clients or facilitators
image.png (view on web)
I am likely not understanding the right combination of permissions to set, but wanted to confirm.

**Comment by deb761** [comment]
Check the profile to make sure it doesn’t include the extra fields. Sent from my iPhoneOn Aug 8, 2024, at 9:49 AM, atlasjen ***@***.***> wrote:﻿
I tried out changing the permission sets and public groups on Niki Becker in staging. My goal was to set her as someone who had the "team" permissions but not anything else.  I discovered this while testing out visibility of dog.
She is Advanced Standard User profile and then has these assignments:
image.png (view on web)
image.png (view on web)
I removed her from the All public access group.
We still have two extraneous fields:
image.png (view on web)
And she can see a lot of contacts besides clients or facilitators
image.png (view on web)
I am likely not understanding the right combination of permissions to set, but wanted to confirm.

**Comment by atlasjen** [comment]
as agreed for this release, if someone has team they have to have adv standard user, so they will see all contacts. closing for this release. we will want to figure out the right base permission sets to be able to build up the various views in addition to volunteer, but that can be next release

**Comment by deb761** [comment]
Actually, it's not Advanced Standard User they need, its `Puppy Raiser`
