### ISSUE TITLE
Prod release 1.9- Volunteer permissions issues

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#559]
I logged in as Peony.

1. Files that shouldn't be seen:
If a user is a volunteer and something else, like a client or board member, i can presently see all of their files, not just volunteer files.
For example, this is a client
![image](https://github.com/user-attachments/assets/ee005534-b312-483f-be9d-b2e608b0eeb5)
This appears to work as expected in staging, so some setting must not have gotten propegated over.

2. Contacts that shouldn't be seen are
For some reason my own contact is visible to her, but I am not listed as a volunteer.
I assumed it was if I was a volunteer's emergency contact, but i am not. I am a related contact for a volunteer but not their emergency contact.

In staging i was using Alexandra Foley and Bruce Scott contacts to experiment with this.
Alexandra Foley is a volunteer. Bruce Scott is not.
When Alexander folder was bruce's emergency contact, which mean viewing from alexandra's record you have this:
![image](https://github.com/user-attachments/assets/ee07d3ae-4dfa-4145-8c98-4875937d001c)
I could see bruce's contact, which is expected.

When i had the relationship the other way around, so bruce had alexandra as his emergency contact and this is what you saw on Alexandra's record
![image](https://github.com/user-attachments/assets/7f0ed54e-3ce8-4b48-9e6d-950151363a62)

when logged in as peony, bruce's contact record doesn't show. 
![image](https://github.com/user-attachments/assets/d57cb00c-adc6-432a-b01a-a435734dc9a3)
again this is expected. This is different than the behavior in prod, however, so again, something isn't configured quite right in prod.

**Comment by deb761** [comment]
Doh!  I forgot to set the Group field in Category Rules.

**Comment by atlasjen** [comment]
confirmed good in latest production patch on 8/12/24. closing
