### ISSUE TITLE
Prod 1.9: All related files now showing on contact

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#560]
I missed this in staging, as it is also an issue there.
Go look at my record.. you will see tons and tons of related files. This used to only show 6. It still counts up to 6, but it shows all files.

![image](https://github.com/user-attachments/assets/a83c56fb-7f72-4f21-bcb2-76bfe1b60521)
Note, this data continues, i cut it off.

**Comment by deb761** [comment]
Doh!  I couldn't use Limit because of later filtering, and forgot to shorten the list....
