### ISSUE TITLE
permission error editing tasks- prod 1.9

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#563]
This is in prod 1.9.
Molly just let me know she tried to edit a comment on a task and got an error.
I was able to do an edit as my user, but when i logged in as her i was able to reproduce it.

![image](https://github.com/user-attachments/assets/1f71c5dd-cef4-4930-934f-58eaec940119)

**Comment by atlasjen** [comment]
this is a task Laura created and assigned to herself. Molly cannot edit the comments on it.

Molly is able to edit comments on her own tasks.

**Comment by atlasjen** [comment]
Adding in feedback from support here: 
We enabled logging and had molly directly reproduce. interestingly me logged in as her didn't create the same error logs.
There are several logs here: https://atlasassistancedogs.lightning.force.com/lightning/setup/ApexDebugLogs/home

this is the only one with an error:
![image](https://github.com/user-attachments/assets/189ef885-cc30-46d7-bedf-7084f5a796b6)

and here is a screen shot of the that one

![image](https://github.com/user-attachments/assets/f6bdf936-5dca-4d5e-acdf-c4542290ebf7)

support said to see if there is a field in the query that molly might not have access to. apparently tasks inherit permissions from the contact they are on.

this is a pretty common workflow use case for molly and laura, so it would be good to figure out as soon as we can. support isn't going to go any further in debugging from what i can tell, as this relates to a custom managed package.

**Comment by deb761** [comment]
I found the bit of code that the log is referencing, and:

1. Notice the `Success` status, there is NO error.
2. The log has a return for a SOQL statement with one record.
3. The SOQL statement is in the PositionStatusController, which shows the status for each position in the record page, nothing associated with Tasks here.

I will see if I can reproduce this in a scratch org.

**Comment by atlasjen** [comment]
Yeah, I noticed that as well re no errors. The support person’s view was this is the only data that was reported when doing the action, so she thought that was likely the cause of the error… but indeed, the error isn’t logged

**Comment by deb761** [comment]
I did a bit of research, and the edit error Molly bumped into has absolutely nothing to do with the managed package, which has no Tasks defined directly, but everything to do with how Salesforce provides access to Tasks:

https://help.salesforce.com/s/articleView?id=000385354&type=1

I solved the problem by changing Activity permissions to `Controlled by parent`.

**Comment by atlasjen** [comment]
woot! confirming this is happy in prod. closing. this release is done :)
