### ISSUE TITLE
update File upload controller to allow name to be edited

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#569]
In some cases there are 2 versions of a file uploaded, such as a word version or excel version and a pdf. There is no way to tell from looking at the file list which is which.

For example:
![image](https://github.com/user-attachments/assets/f382ec79-38b7-4f9f-beb5-aaf0aceeb469)

In reading through salesforce documentation, it doesn't appear this can be changed by default, but one recommendation was to manually edit the file name.
https://ideas.salesforce.com/s/idea/a0B8W00000GdiKuUAJ/extensions-need-to-be-visible-in-files
however, since we have a custom file handler, when i click edit, i can't edit the filename.

What would be ideal is to either
- show the extension by default (not sure if we can since it is a custom component)
- allow the filename to be edited after it is dragged up

We will also modify business process just to name the pdf one differently, but this is a nice to have if not too hard to change.

**Comment by deb761** [comment]
Salesforce does store the file type as a field in Content Version:
<img width="1604" alt="image" src="https://github.com/user-attachments/assets/d13f30eb-4bfc-4d40-9a40-cffe586a34c7">

**Comment by deb761** [comment]
Do you also want to edit the file name/title?

**Comment by atlasjen** [comment]
no need to edit the name. i like the solution you came up with showing the file type.
