### ISSUE TITLE
READY FOR STAGING&PROD-Outlook email integration

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#65]
We migrated outlook email configuration, but need to try out actual flow and see how to make it more useful.
Need to setup for Molly and Jen in new org.

**Comment by SandeepSF461** [comment]
This is been ready and reviewed by Jen in Devint.
The next actions would be for Jen to test it as a user and will be ready to move in when we are ready to go live.

**Comment by atlasjen** [comment]
ready to do setup in staging and prod.

**Comment by atlasjen** [comment]
closing. this is ready.
