### ISSUE TITLE
"Edit" on Contact results in a New Recurring Donation page and errors

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#78]
I found this testing in Arjinders branch, but it is also present in dev.
If you create a contact and then click Edit on the contact, there is a delay and then a dialog pops up for New Recurring donation and then there are errors.

Error I saw on Arjinder's branch (new-code-form):
![image](https://user-images.githubusercontent.com/66139437/120121179-d92ec000-c156-11eb-9d1b-a20fd9dc1e8d.png)

Error I saw on DevInt
![image](https://user-images.githubusercontent.com/66139437/120121197-ed72bd00-c156-11eb-8245-476bc62c1230.png)

Eventually followed by another error that I can't seem to get to repro.

**Comment by deb761** [comment]
Included in beta release 1.0 (Beta 2)

**Comment by atlasjen** [comment]
Included in production release 1.0
