### ISSUE TITLE
update lead page layout to match lead input form

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#87]
Can you update the Lead page layout to include all data in the lead NEW form and tweak cosmetically? I like how you've been doing layouts, so use your judgement.
let me know if you need other guidance.

**Comment by kaurarjinder** [comment]
Sure, will do that.

Thanks!

**Comment by atlasjen** [comment]
I have confirmed the datamodel, contact Us form and New lead form all are consistent. :) 
What remains is:
In the Lead object:
Move "activity" and "chatter" from being tabs in the main section and to the right Quick access area.. this is consistent w/ how Client is setup.

If "related" applies to lead, add "related" as a tab in the main section.
Remove "news" as a tab in the main section.
With this change, lead layout is done other then the mappings from the contact us form once live.

**Comment by atlasjen** [comment]
closing. resolved.
