### ISSUE TITLE
update summary view for "Leads"

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#88]
These are changes to the summary you see when you click on Leads.

(1)I want to have the following fields in order
Name, State/Province, Mobile, Email, Lead Interest, Lead Status, Created Date, Owner Alias, Unread by Owner

I do not see anyway to add Lead Interest.
(2) related to above I'd like to add a filter of Lead Interest but that is not an option.

Please figure out why we can't and then change to display these.
Note, i am trying this in the devint sandbox as of 7/10/21

**Comment by atlasjen** [comment]
@SandeepSF461  can you confirm if "mobile" is where we map the phone # to in lead or if it is to a diff field?
thanks!

**Comment by SandeepSF461** [comment]
@atlasjen we have two fields one is **mobile** and another one is **phone** on the lead object jen. Both are standard fields provided by Salesforce. In the previous process, we have mapped it to Phone field on account. So, I believe it's the Phone field that we map into lead.

**Comment by deb761** [comment]
The label for Lead Interest is just "Interest".

**Comment by deb761** [comment]
Included in beta release 1.0 (Beta 2)

**Comment by atlasjen** [comment]
Included in production release 1.0
